import React from "react";

type Social={platform?:string;handle?:string;followers?:number;engagementRate?:number;averageViews?:number;averageViewsMin?:number;averageViewsMax?:number;contentStyle?:string;url?:string};
type Rate={platform?:string;serviceName?:string;service_name?:string;price?:number;currency?:string;description?:string};
type Profile={username?:string;displayName?:string;display_name?:string;bio?:string;category?:string;location?:string;avatarUrl?:string;avatar_url?:string;coverUrl?:string;cover_url?:string;contactEmail?:string;contact_email?:string;whatsapp?:string;theme?:string;language?:"id"|"en"};
type Experience={label?:string}; type Term={content?:string};
const n=(v:any)=>Number(v||0);
const name=(p:Profile)=>p.displayName||p.display_name||"Creator Name";
const avatar=(p:Profile)=>p.avatarUrl||p.avatar_url||"";
const cover=(p:Profile)=>p.coverUrl||p.cover_url||"";
const compact=(v:number,lang:"id"|"en")=>new Intl.NumberFormat(lang==="id"?"id-ID":"en-US",{notation:"compact",maximumFractionDigits:1}).format(v||0);
const money=(v:number,c="IDR")=>{try{return new Intl.NumberFormat(c==="IDR"?"id-ID":"en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(v||0)}catch{return `${c} ${n(v).toLocaleString()}`}};
const rateName=(r:Rate)=>r.serviceName||r.service_name||"Service";
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:2}).format(n(v))}%`;
const viewRange=(s:Social,lang:"id"|"en")=>{const a=n(s.averageViewsMin),b=n(s.averageViewsMax),fmt=(x:number)=>new Intl.NumberFormat(lang==="id"?"id-ID":"en-US",{notation:"compact",maximumFractionDigits:1}).format(x||0);if(a||b)return `${fmt(a||b)} – ${fmt(b||a)}`;return fmt(n(s.averageViews))};
const mail=(p:Profile)=>p.contactEmail||p.contact_email||"";
const waDigits=(v?:string)=>String(v||"").replace(/\D/g,"").replace(/^0/,"62");
const waLink=(v?:string)=>waDigits(v)?`https://wa.me/${waDigits(v)}`:"";
const slug=(v?:string)=>(v||"social").toLowerCase().replace(/[^a-z0-9]+/g,"-");
const cleanHandle=(v?:string)=>String(v||"").trim().replace(/^@/,"");
function socialLink(s:Social){if(s.url?.trim()){const x=s.url.trim();return /^https?:\/\//i.test(x)?x:`https://${x}`;}const h=cleanHandle(s.handle);if(!h)return "";const p=(s.platform||"").toLowerCase();if(p==="instagram")return `https://instagram.com/${h}`;if(p==="tiktok")return `https://www.tiktok.com/@${h}`;if(p==="facebook")return `https://facebook.com/${h}`;if(p==="youtube")return `https://youtube.com/${h.startsWith("@")?h:`@${h}`}`;if(p==="x"||p==="twitter")return `https://x.com/${h}`;return ""}

export function SocialIcon({platform,size=18}:{platform?:string;size?:number}){const p=(platform||"").toLowerCase();const C={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.7,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(p==="instagram")return <svg {...C}><rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="3.8"/><circle cx="17.3" cy="6.8" r=".9" fill="currentColor" stroke="none"/></svg>;if(p==="tiktok")return <svg {...C}><path d="M14 4v10.2a4.2 4.2 0 1 1-3.4-4.1"/><path d="M14 4c1.15 2.35 2.9 3.6 5 3.8"/></svg>;if(p==="youtube")return <svg {...C}><rect x="3" y="6.5" width="18" height="11" rx="3"/><path d="m10 9.5 5 2.5-5 2.5Z"/></svg>;if(p==="facebook")return <svg {...C}><path d="M14.2 7.2h2.6V3.8h-2.9c-3 0-4.8 1.9-4.8 5v2.3H6.5v3.5h2.6v5.6h3.7v-5.6h3.1l.7-3.5h-3.8V8.8c0-1.05.35-1.6 1.4-1.6Z"/></svg>;if(p==="x"||p==="twitter")return <svg {...C}><path d="M5 4.5 19 19.5M18.5 4.5 5.5 19.5"/></svg>;return <svg {...C}><circle cx="12" cy="12" r="8.5"/><path d="M3.5 12h17"/></svg>}
function LocationIcon({size=15}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>}
function MailIcon({size=18}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m4 7 8 6 8-6"/></svg>}
function WhatsAppIcon({size=18}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M20 11.6a8 8 0 0 1-11.7 7.1L4 20l1.3-4.1A8 8 0 1 1 20 11.6Z"/><path d="M9.1 8.2c.3 2.7 2 4.6 4.7 5.6l1.2-1.2 2 .8c-.3 1.5-1.2 2.4-2.7 2.4-3.7-.4-6.9-3.7-7.2-7.4 0-1.3.7-2.2 2-2.5l.8 2.1-.8.2Z"/></svg>}

const language=(p:Profile)=>p.language||"id";
function labels(lang:"id"|"en"){return lang==="id"?{about:"Statistik Social Media",followers:"Followers",eng:"Engagement Rate",views:"Rata-rata Views",style:"Content Style",rates:"Rate Kerja Sama",platform:"Platform",type:"Jenis Konten",desc:"Deskripsi",price:"Harga",contact:"Hubungi Saya",email:"Email",wa:"WhatsApp",experience:"Pengalaman Kolaborasi",terms:"Syarat & Ketentuan"}:{about:"Social Media Stats",followers:"Followers",eng:"Engagement Rate",views:"Average Views",style:"Content Style",rates:"Collaboration Rates",platform:"Platform",type:"Content Type",desc:"Description",price:"Price",contact:"Contact Me",email:"Email",wa:"WhatsApp",experience:"Collaboration Experience",terms:"Terms & Conditions"}}
function Avatar({p,className=""}:{p:Profile;className?:string}){return avatar(p)?<img className={`v7Avatar ${className}`} src={avatar(p)} alt={name(p)}/>:<div className={`v7Avatar v7Fallback ${className}`}>{name(p).slice(0,1)}</div>}
function Hero({p,className=""}:{p:Profile;className?:string}){const src=cover(p)||avatar(p);return src?<img className={`v7Hero ${className}`} src={src} alt={name(p)}/>:<div className={`v7Hero v7HeroFallback ${className}`}>{name(p).slice(0,1)}</div>}
function SocialLogo({s}:{s:Social}){return <span className={`v7SocialLogo platform-${slug(s.platform)}`}><SocialIcon platform={s.platform} size={20}/></span>}
function SocialTop({s}:{s:Social}){const href=socialLink(s);const body=<><SocialLogo s={s}/><div><strong>{s.platform||"Social"}</strong>{s.handle&&<small>{s.handle}</small>}</div></>;return href?<a className="v7SocialTop v7SocialLink" href={href} target="_blank" rel="noopener noreferrer" aria-label={`Open ${s.platform||"social"} profile`}>{body}<span className="v7External" aria-hidden="true">↗</span></a>:<div className="v7SocialTop">{body}</div>}
function SocialTiles({socials,lang,mode="cards"}:{socials:Social[];lang:"id"|"en";mode?:"cards"|"rows"}){const L=labels(lang);return <div className={`v7Socials v7Socials-${mode}`}>{socials.map((s,i)=><article className={`v7Social ${mode} platform-card-${slug(s.platform)}`} key={`${s.platform}-${i}`}><SocialTop s={s}/><div className="v7Stat"><b>{compact(n(s.followers),lang)}</b><span>{L.followers}</span></div><div className="v7Stat"><b>{pct(n(s.engagementRate))}</b><span>{L.eng}</span></div><div className="v7Stat"><b>{viewRange(s,lang)}</b><span>{L.views}</span></div><p className="v7ContentStyle"><strong>{L.style}:</strong> {s.contentStyle||"-"}</p></article>)}</div>}
function RateTable({rates,lang}:{rates:Rate[];lang:"id"|"en"}){const L=labels(lang);return <div className="v7RateWrap"><div className="v7RateTable"><div className="v7RateRow v7RateHead"><span>{L.platform}</span><span>{L.type}</span><span>{L.price}</span><span>{L.desc}</span></div>{rates.map((r,i)=><div className="v7RateRow" key={i}><span>{r.platform||"-"}</span><strong>{rateName(r)}</strong><b>{money(n(r.price),r.currency||"IDR")}</b><span>{r.description||"-"}</span></div>)}</div></div>}
function Contact({p,lang}:{p:Profile;lang:"id"|"en"}){const L=labels(lang),email=mail(p),wa=waLink(p.whatsapp);if(!email&&!wa)return null;return <div className="v7Contacts">{email&&<a href={`mailto:${email}`} className="v7Contact"><span className="v7ContactMark"><MailIcon/></span><span><small>{L.email}</small><strong>{email}</strong></span></a>}{wa&&<a href={wa} target="_blank" rel="noopener noreferrer" className="v7Contact wa"><span className="v7ContactMark"><WhatsAppIcon/></span><span><small>{L.wa}</small><strong>{p.whatsapp}</strong></span></a>}</div>}
function ListBlock({title,items,type}:{title:string;items:(Experience|Term)[];type:"experience"|"term"}){if(!items.length)return null;return <section className="v7ListBlock"><h3>{title}</h3><ul>{items.map((x:any,i)=><li key={i}>{type==="experience"?x.label:x.content}</li>)}</ul></section>}
function Section({title,children,className=""}:{title:string;children:React.ReactNode;className?:string}){return <section className={`v7Section ${className}`}><div className="v7SectionTitle"><h2>{title}</h2><span/></div>{children}</section>}
function Location({text}:{text?:string}){return text?<small className="v7Location"><LocationIcon/>{text}</small>:null}
function PublicRateLink({p}:{p:Profile}){const username=(p.username||"").trim();if(!username)return null;const href=`https://ratecard.wholegacy.com/${username}`;return <footer className="v7PublicLink"><a href={href} target="_blank" rel="noopener noreferrer">{href.replace(/^https?:\/\//,"")}</a></footer>}
function Identity({p,variant="normal"}:{p:Profile;variant?:"normal"|"dark"}){return <div className={`v7Identity ${variant}`}><Avatar p={p}/><div className="v7IdentityText"><h1>{name(p)}</h1><p>{p.category||"Content Creator"}</p><Location text={p.location}/></div></div>}


function Modern({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const lang=language(p),L=labels(lang);return <article className="rateTemplate v7Template tplModern7"><header className="v7ModernHero"><Hero p={p}/><div className="v7ModernWords"><b>GOOD CONTENT</b><span>BRIGHTER STORIES</span></div></header><div className="v7ModernProfile"><Avatar p={p}/><div className="v7IdentityText"><h1>{name(p)}</h1><p>{p.category||"Content Creator"}</p><Location text={p.location}/></div></div>{p.bio&&<p className="v7Bio modernBio">{p.bio}</p>}<Section title={L.about}><SocialTiles socials={socials} lang={lang}/></Section><Section title={L.rates}><RateTable rates={rates} lang={lang}/></Section><div className="v7LowerGrid"><Section title={L.contact}><Contact p={p} lang={lang}/></Section><ListBlock title={L.experience} items={experiences} type="experience"/></div><ListBlock title={L.terms} items={terms} type="term"/><PublicRateLink p={p}/></article>}
function Minimal({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const lang=language(p),L=labels(lang);return <article className="rateTemplate v7Template tplMinimal7"><header className="v7MinimalHero"><Hero p={p}/></header><div className="v7MinimalIdentity"><Identity p={p}/>{p.bio&&<p className="v7Bio">{p.bio}</p>}</div><Section title={L.about}><SocialTiles socials={socials} lang={lang} mode="rows"/></Section><Section title={L.rates}><RateTable rates={rates} lang={lang}/></Section><div className="v7LowerGrid"><Section title={L.contact}><Contact p={p} lang={lang}/></Section><ListBlock title={L.experience} items={experiences} type="experience"/></div><ListBlock title={L.terms} items={terms} type="term"/><PublicRateLink p={p}/></article>}
function CreatorPro({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const lang=language(p),L=labels(lang);return <article className="rateTemplate v7Template tplCreator7"><header className="v7CreatorHero"><div className="v7Tape tapeA"/><div className="v7CreatorSlogan">EXPLORE<br/>CREATE ☺<br/>INSPIRE</div><div className="v7CreatorPhoto"><Hero p={p}/></div><div className="v7Sticky">GOOD<br/>STORIES<br/>MATTER</div></header><div className="v7CreatorProfile"><Avatar p={p}/><div className="v7IdentityText"><h1>{name(p)}</h1><p>{p.category||"Content Creator"}</p><Location text={p.location}/></div></div>{p.bio&&<p className="v7Bio creatorBio7">{p.bio}</p>}<Section title={L.about}><SocialTiles socials={socials} lang={lang}/></Section><Section title={L.rates}><RateTable rates={rates} lang={lang}/></Section><div className="v7CreatorBottom"><Section title={L.contact}><Contact p={p} lang={lang}/></Section><ListBlock title={L.experience} items={experiences} type="experience"/></div><ListBlock title={L.terms} items={terms} type="term"/><PublicRateLink p={p}/></article>}
function DarkPro({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const lang=language(p),L=labels(lang);return <article className="rateTemplate v7Template tplDark7"><header className="v7DarkHero"><Hero p={p}/><div className="v7DarkOverlay"><span>PEOPLE · PLACES · PERSPECTIVE</span></div></header><div className="v7DarkIdentity"><Identity p={p} variant="dark"/>{p.bio&&<p className="v7Bio">{p.bio}</p>}</div><Section title={L.about}><SocialTiles socials={socials} lang={lang}/></Section><Section title={L.rates}><RateTable rates={rates} lang={lang}/></Section><div className="v7LowerGrid"><Section title={L.contact}><Contact p={p} lang={lang}/></Section><ListBlock title={L.experience} items={experiences} type="experience"/></div><ListBlock title={L.terms} items={terms} type="term"/><PublicRateLink p={p}/></article>}

export default function RatecardTemplates({profile,socials=[],rates=[],experiences=[],terms=[],theme}:{profile:Profile;socials?:Social[];rates?:Rate[];experiences?:Experience[];terms?:Term[];theme?:string}){const t=theme||profile.theme||"minimal";const props={p:profile,socials,rates,experiences,terms};if(t==="editorial")return <Modern {...props}/>;if(t==="creator")return <CreatorPro {...props}/>;if(t==="dark-pro")return <DarkPro {...props}/>;return <Minimal {...props}/>}
