"use client";
import { ChangeEvent, useMemo, useRef, useState } from "react";
import RatecardTemplates, { SocialIcon } from "@/components/ratecard-templates";

type AnyRow=Record<string,any>;
const platforms=["Instagram","TikTok","Facebook","YouTube","X"];
const emptySocial=()=>({platform:"Instagram",handle:"",url:"",followers:0,engagementRate:0,averageViewsMin:0,averageViewsMax:0,contentStyle:""});
const emptyRate=()=>({platform:"Instagram",serviceName:"Reels",price:0,currency:"IDR",description:""});

export default function DashboardClient({user,profile,initialSocials,initialRates,initialExperiences,initialTerms}:{user:AnyRow;profile:AnyRow;initialSocials:AnyRow[];initialRates:AnyRow[];initialExperiences:AnyRow[];initialTerms:AnyRow[]}){
 const [tab,setTab]=useState("overview"),[message,setMessage]=useState(""),[uploading,setUploading]=useState<"avatar"|"cover"|"">(""),[previewOpen,setPreviewOpen]=useState(false);
 const avatarRef=useRef<HTMLInputElement>(null),coverRef=useRef<HTMLInputElement>(null);
 const [p,setP]=useState({username:profile.username||"",displayName:profile.display_name||"",bio:profile.bio||"",category:profile.category||"",location:profile.location||"",avatarUrl:profile.avatar_url||"",coverUrl:profile.cover_url||"",contactEmail:profile.contact_email||user.email,whatsapp:profile.whatsapp||"",theme:profile.theme||"editorial",published:Boolean(profile.published)});
 const [socials,setSocials]=useState(initialSocials.map(x=>({platform:x.platform,handle:x.handle,url:x.url,followers:Number(x.followers||0),engagementRate:Number(x.engagement_rate||0),averageViewsMin:Number(x.average_views_min||0),averageViewsMax:Number(x.average_views_max||0),contentStyle:x.content_style||""})));
 const [rates,setRates]=useState(initialRates.map(x=>({platform:x.platform,serviceName:x.service_name,price:Number(x.price||0),currency:x.currency||"IDR",description:x.description||""})));
 const [experiences,setExperiences]=useState(initialExperiences.map(x=>({label:x.label||""})));
 const [terms,setTerms]=useState(initialTerms.map(x=>({content:x.content||""})));
 const publicUrl=useMemo(()=>`https://ratecard.wholegacy.com/${p.username}`,[p.username]);
 const flash=(t:string)=>{setMessage(t);setTimeout(()=>setMessage(""),3000)};
 async function saveProfile(silent=false){const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});const d=await r.json();if(!silent)flash(r.ok?"Profile tersimpan.":d.error||"Gagal menyimpan.");return r.ok}
 async function saveSocials(silent=false){const r=await fetch("/api/socials",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:socials})});const d=await r.json();if(!silent)flash(r.ok?"Tentang account tersimpan.":d.error||"Gagal menyimpan.");return r.ok}
 async function saveRates(silent=false){const r=await fetch("/api/rates",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:rates})});const d=await r.json();if(!silent)flash(r.ok?"Rate kerjasama tersimpan.":d.error||"Gagal menyimpan.");return r.ok}
 async function saveExperiences(silent=false){const r=await fetch("/api/experiences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:experiences})});if(!silent)flash(r.ok?"Pengalaman kolaborasi tersimpan.":"Gagal menyimpan.");return r.ok}
 async function saveTerms(silent=false){const r=await fetch("/api/terms",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:terms})});if(!silent)flash(r.ok?"Syarat & ketentuan tersimpan.":"Gagal menyimpan.");return r.ok}
 async function publish(){const ok=(await saveProfile(true))&&(await saveSocials(true))&&(await saveRates(true))&&(await saveExperiences(true))&&(await saveTerms(true));if(!ok){flash("Periksa data sebelum publish.");return}const r=await fetch("/api/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({published:true})});const d=await r.json();if(r.ok){setP(v=>({...v,published:true}));flash("Rate card berhasil dipublish.")}else flash(d.error||"Publish gagal.")}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/login"}
 async function upload(kind:"avatar"|"cover",e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(kind);const fd=new FormData();fd.append("file",file);fd.append("kind",kind);const r=await fetch("/api/upload",{method:"POST",body:fd});const d=await r.json();if(r.ok){setP(v=>({...v,[kind==="avatar"?"avatarUrl":"coverUrl"]:d.url}));flash("Upload berhasil. Klik Save Profile untuk menyimpan.")}else flash(d.error||"Upload gagal.");setUploading("");e.target.value=""}
 const preview=<RatecardTemplates profile={p} socials={socials} rates={rates} experiences={experiences} terms={terms} theme={p.theme}/>;
 const menu=["overview","profile","account","rates","contact","experience","terms","design"];
 return <main className="dashboard"><div className="container dashboardGrid"><aside className="sidebar"><div className="brand">Wholegacy<span>.</span></div><small>Ratecard CMS v4</small><nav>{menu.map(m=><button key={m} className={tab===m?"sideActive":""} onClick={()=>setTab(m)}>{({account:"Tentang Account",rates:"Rate Kerjasama",contact:"Hubungi Saya",experience:"Pengalaman Kolaborasi",terms:"Syarat & Ketentuan"} as any)[m]||m[0].toUpperCase()+m.slice(1)}</button>)}</nav><button className="logoutBtn" onClick={logout}>Logout</button></aside><section className="dashMain">{message&&<div className="toast">{message}</div>}<div className="dashTop"><div><span className="statusPill">{p.published?"Published":"Draft"}</span><h1>{tab==="overview"?`Hi, ${p.displayName}`:"Rate Card Editor"}</h1></div><div className="topActions"><button className="button secondary mobilePreviewBtn" onClick={()=>setPreviewOpen(true)}>Live Preview</button><a className="button secondary" target="_blank" href={`/${p.username}`}>Public page</a><button className="button primary" onClick={publish}>Publish</button></div></div><div className="cmsLiveLayout"><div className="cmsEditor">
 {tab==="overview"&&<><p className="dashLead">CMS mengikuti struktur rate card: data akun, rate kerjasama, kontak, pengalaman kolaborasi, syarat & ketentuan, lalu pilih desain.</p><div className="dashCards"><div className="dashCard"><span>Public URL</span><strong className="smallStrong">/{p.username}</strong><a href={`/${p.username}`} target="_blank">Open profile</a></div><div className="dashCard"><span>Social accounts</span><strong>{socials.length}</strong></div><div className="dashCard"><span>Rate items</span><strong>{rates.length}</strong></div></div><div className="publicUrlBox"><span>Creator link</span><code>{publicUrl}</code></div></>}
 {tab==="profile"&&<Card title="Profil Creator" subtitle="Foto, nama, bio, niche dan lokasi."><div className="uploadGrid"><Upload title="Avatar" value={p.avatarUrl} round busy={uploading==="avatar"} onClick={()=>avatarRef.current?.click()}/><Upload title="Cover / foto utama" value={p.coverUrl} busy={uploading==="cover"} onClick={()=>coverRef.current?.click()}/></div><input ref={avatarRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload("avatar",e)}/><input ref={coverRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload("cover",e)}/><Grid><Field label="Display name"><input value={p.displayName} onChange={e=>setP(v=>({...v,displayName:e.target.value}))}/></Field><Field label="Username"><input value={p.username} onChange={e=>setP(v=>({...v,username:e.target.value}))}/></Field><Field label="Category / Niche"><input value={p.category} onChange={e=>setP(v=>({...v,category:e.target.value}))}/></Field><Field label="Location"><input value={p.location} onChange={e=>setP(v=>({...v,location:e.target.value}))}/></Field></Grid><Field label="Bio"><textarea value={p.bio} onChange={e=>setP(v=>({...v,bio:e.target.value}))}/></Field><button className="button primary" onClick={()=>saveProfile()}>Save profile</button></Card>}
 {tab==="account"&&<Card title="Tentang Account" subtitle="Setiap platform punya logo dan statistik sendiri. Tema editorial memakai account pertama sebagai fokus utama.">{socials.map((s,i)=><div className="itemEditor" key={i}><div className="socialEditorHead"><div className="socialLogoBadge"><SocialIcon platform={s.platform} size={22}/></div><strong>{s.platform}</strong></div><Grid><Field label="Platform"><select value={s.platform} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,platform:e.target.value}:x))}>{platforms.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Handle"><input value={s.handle} placeholder="@username" onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,handle:e.target.value}:x))}/></Field><Field label="Followers"><input type="number" value={s.followers} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,followers:Number(e.target.value)}:x))}/></Field><Field label="Engagement rate (%)"><input type="number" step="0.01" value={s.engagementRate} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,engagementRate:Number(e.target.value)}:x))}/></Field><Field label="Average views minimum"><input type="number" value={s.averageViewsMin} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,averageViewsMin:Number(e.target.value)}:x))}/></Field><Field label="Average views maximum"><input type="number" value={s.averageViewsMax} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,averageViewsMax:Number(e.target.value)}:x))}/></Field></Grid><Field label="Content style"><input value={s.contentStyle} placeholder="Aesthetic, Elegan, Authentic & Relatable" onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,contentStyle:e.target.value}:x))}/></Field><button className="textButton danger" onClick={()=>setSocials(v=>v.filter((_,j)=>j!==i))}>Remove</button></div>)}<div className="rowActions"><button className="button secondary" onClick={()=>setSocials(v=>[...v,emptySocial()])}>+ Add account</button><button className="button primary" onClick={()=>saveSocials()}>Save account data</button></div></Card>}
 {tab==="rates"&&<Card title="Rate Kerjasama" subtitle="Jenis konten, deskripsi dan harga.">{rates.map((r,i)=><div className="itemEditor" key={i}><Grid><Field label="Platform"><select value={r.platform} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,platform:e.target.value}:x))}>{platforms.map(x=><option key={x}>{x}</option>)}<option>Other</option></select></Field><Field label="Jenis Konten"><input value={r.serviceName} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,serviceName:e.target.value}:x))}/></Field><Field label="Harga"><input type="number" value={r.price} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></Field><Field label="Currency"><select value={r.currency} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,currency:e.target.value}:x))}><option>IDR</option><option>USD</option><option>SGD</option></select></Field></Grid><Field label="Deskripsi"><input value={r.description} placeholder="Video berdiri sendiri, maks. 60 detik" onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></Field><button className="textButton danger" onClick={()=>setRates(v=>v.filter((_,j)=>j!==i))}>Remove</button></div>)}<div className="rowActions"><button className="button secondary" onClick={()=>setRates(v=>[...v,emptyRate()])}>+ Add rate</button><button className="button primary" onClick={()=>saveRates()}>Save rates</button></div></Card>}
 {tab==="contact"&&<Card title="Hubungi Saya" subtitle="Kontak bisnis tampil dengan ikon email dan WhatsApp."><Grid><Field label="Email"><input type="email" value={p.contactEmail} onChange={e=>setP(v=>({...v,contactEmail:e.target.value}))}/></Field><Field label="WhatsApp"><input value={p.whatsapp} placeholder="62812..." onChange={e=>setP(v=>({...v,whatsapp:e.target.value}))}/></Field></Grid><button className="button primary" onClick={()=>saveProfile()}>Save contact</button></Card>}
 {tab==="experience"&&<Card title="Pengalaman Kolaborasi" subtitle="Contoh: Fashion (Local Brand), Beauty & Skincare, F&B.">{experiences.map((x,i)=><div className="inlineList" key={i}><input value={x.label} onChange={e=>setExperiences(v=>v.map((a,j)=>j===i?{label:e.target.value}:a))}/><button className="textButton danger" onClick={()=>setExperiences(v=>v.filter((_,j)=>j!==i))}>Remove</button></div>)}<div className="rowActions"><button className="button secondary" onClick={()=>setExperiences(v=>[...v,{label:""}])}>+ Add experience</button><button className="button primary" onClick={()=>saveExperiences()}>Save experiences</button></div></Card>}
 {tab==="terms"&&<Card title="Syarat & Ketentuan" subtitle="Buat poin-poin kerja sama yang akan tampil di rate card.">{terms.map((x,i)=><div className="inlineList" key={i}><textarea value={x.content} onChange={e=>setTerms(v=>v.map((a,j)=>j===i?{content:e.target.value}:a))}/><button className="textButton danger" onClick={()=>setTerms(v=>v.filter((_,j)=>j!==i))}>Remove</button></div>)}<div className="rowActions"><button className="button secondary" onClick={()=>setTerms(v=>[...v,{content:""}])}>+ Add term</button><button className="button primary" onClick={()=>saveTerms()}>Save terms</button></div></Card>}
 {tab==="design"&&<Card title="Pilih Tema Design" subtitle="Setiap tema memakai struktur layout berbeda. Editorial Beige dibuat mengikuti struktur referensi yang kamu kirim."><ThemePicker value={p.theme} set={theme=>setP(v=>({...v,theme}))}/><button className="button primary" onClick={()=>saveProfile()}>Save design</button></Card>}
 </div><aside className="livePreviewPane"><div className="previewSticky"><div className="previewBar"><span>LIVE PREVIEW</span><small>Changes appear instantly</small></div><div className="previewDevice">{preview}</div></div></aside></div></section></div>{previewOpen&&<div className="previewModal"><button className="previewClose" onClick={()=>setPreviewOpen(false)}>Close</button><div className="previewModalInner">{preview}</div></div>}</main>
}
function ThemePicker({value,set}:{value:string;set:(v:string)=>void}){return <div className="themeGrid">{[["editorial","Editorial Beige","Template detail seperti referensi"],["minimal","Minimal","Clean & simple"],["creator","Creator","Image-first & social"],["dark-pro","Dark Pro","Premium split layout"]].map(([id,n,d])=><button key={id} className={`themeCard ${value===id?"selected":""}`} onClick={()=>set(id)}><div className={`themePreview ${id}`}><span>{n}</span><i/><i/><i/></div><strong>{n}</strong><small>{d}</small></button>)}</div>}
function Upload({title,value,busy,onClick,round=false}:{title:string;value:string;busy:boolean;onClick:()=>void;round?:boolean}){return <button type="button" className="uploadBox" onClick={onClick}><div className={`uploadThumb ${round?"round":""}`}>{value?<img src={value} alt={title}/>:<span>+</span>}</div><div><strong>{busy?"Uploading...":title}</strong><small>{value?"Click to replace":"JPG, PNG, WebP · max 5 MB"}</small></div></button>}
function Card({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="editorCard templateCmsCard"><div className="templateCmsHead"><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>}
function Grid({children}:{children:React.ReactNode}){return <div className="formGrid">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
