"use client";
import {ChangeEvent,useEffect,useMemo,useRef,useState} from "react";
import {SocialIcon,buildSocialUrl} from "@/components/ratecard-templates";
import SupportLink from "@/components/SupportLink";
import VirtualPreviewFrame from "@/components/VirtualPreviewFrame";
import {resolvePalette,resolveTheme,THEMES} from "@/lib/theme-config";
type AnyRow=Record<string,any>; type Lang="id"|"en";
const platforms=["Instagram","TikTok","Facebook","YouTube","X","Threads","Twitch","LinkedIn"];
const emptySocial=()=>({platform:"Instagram",handle:"",url:"",followers:0,engagementRate:0,averageViewsMin:0,averageViewsMax:0,contentStyle:""});
const emptyRate=()=>({platform:"Instagram",serviceName:"Reels",price:0,currency:"IDR",description:""});
const LIMITS={bio:420,category:100,location:100,contentStyle:100,serviceName:70,description:200,experience:320,terms:420};
const copy={id:{overview:"Overview",profile:"Profil Creator",account:"Tentang Akun",rates:"Rate Kerjasama",contact:"Hubungi Saya",experience:"Pengalaman Kolaborasi",terms:"Syarat & Ketentuan",design:"Desain",logout:"Logout",addAccount:"+ Tambah akun",addRate:"+ Tambah rate",addExperience:"+ Tambah pengalaman",addTerm:"+ Tambah ketentuan",remove:"Hapus",editor:"Rate Card Editor",language:"Bahasa",saved:"Tersimpan.",uploadOk:"Upload berhasil.",uploadFail:"Upload gagal.",prev:"Sebelumnya",next:"Selanjutnya",saving:"Menyimpan...",print:"Print / Download",savePublish:"Save & Publish"},en:{overview:"Overview",profile:"Creator Profile",account:"About Accounts",rates:"Collaboration Rates",contact:"Contact Me",experience:"Collaboration Experience",terms:"Terms & Conditions",design:"Design",logout:"Logout",addAccount:"+ Add account",addRate:"+ Add rate",addExperience:"+ Add experience",addTerm:"+ Add term",remove:"Remove",editor:"Rate Card Editor",language:"Language",saved:"Saved.",uploadOk:"Upload successful.",uploadFail:"Upload failed.",prev:"Prev",next:"Next",saving:"Saving...",print:"Print / Download",savePublish:"Save & Publish"}} as const;

export default function DashboardClient({user,profile,initialSocials,initialRates,initialExperiences,initialTerms}:{user:AnyRow;profile:AnyRow;initialSocials:AnyRow[];initialRates:AnyRow[];initialExperiences:AnyRow[];initialTerms:AnyRow[]}){
 const [tab,setTab]=useState("overview"),[message,setMessage]=useState(""),[uploading,setUploading]=useState<"avatar"|"cover"|"">(""),[savingAction,setSavingAction]=useState<"print"|"publish"|"">("");
 const [previewMode,setPreviewMode]=useState<"desktop"|"mobile">("desktop"),[draftHydrated,setDraftHydrated]=useState(false),[dirty,setDirty]=useState(false);
 const avatarRef=useRef<HTMLInputElement>(null),coverRef=useRef<HTMLInputElement>(null),previewFrameRef=useRef<HTMLIFrameElement>(null);
 const baseTheme=resolveTheme(profile.theme||"cream-editorial");
 const [p,setP]=useState({username:profile.username||"",displayName:profile.display_name||"",bio:profile.bio||"",category:profile.category||"",location:profile.location||"",avatarUrl:profile.avatar_url||"",coverUrl:profile.cover_url||"",contactEmail:profile.contact_email||user.email,whatsapp:profile.whatsapp||"",theme:baseTheme.id,colorPattern:profile.color_pattern||baseTheme.palettes[0].id,language:(profile.language||"id") as Lang,published:Boolean(profile.published)});
 const [socials,setSocials]=useState(initialSocials.map(x=>({platform:x.platform,handle:x.handle,url:"",followers:Number(x.followers||0),engagementRate:Number(x.engagement_rate||0),averageViewsMin:Number(x.average_views_min||0),averageViewsMax:Number(x.average_views_max||0),contentStyle:x.content_style||""})));
 const [rates,setRates]=useState(initialRates.map(x=>({platform:x.platform,serviceName:x.service_name,price:Number(x.price||0),currency:x.currency||"IDR",description:x.description||""})));
 const [experiences,setExperiences]=useState(initialExperiences.map(x=>({label:x.label||""}))); const [terms,setTerms]=useState(initialTerms.map(x=>({content:x.content||""})));
 const t=copy[p.language],draftKey=useMemo(()=>`wholegacy-ratecard-draft:${user.id}`,[user.id]); const publicUrl=useMemo(()=>`https://ratecard.wholegacy.com/${p.username}`,[p.username]);
 const editMenu=["profile","account","rates","contact","experience","terms","design"]; const menu=["overview",...editMenu]; const labels:any={overview:t.overview,profile:t.profile,account:t.account,rates:t.rates,contact:t.contact,experience:t.experience,terms:t.terms,design:t.design};
 const flash=(x:string)=>{setMessage(x);setTimeout(()=>setMessage(""),3200)};
 async function copyPublicUrl(){try{await navigator.clipboard.writeText(publicUrl);flash(p.language==="id"?"Link berhasil disalin.":"Link copied.")}catch{const ta=document.createElement("textarea");ta.value=publicUrl;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove();flash(p.language==="id"?"Link berhasil disalin.":"Link copied.")}}
 useEffect(()=>{try{const raw=localStorage.getItem(draftKey);if(raw){const d=JSON.parse(raw);if(d.p)setP((v:any)=>({...v,...d.p,published:v.published}));if(Array.isArray(d.socials))setSocials(d.socials.map((s:any)=>({...s,url:""})));if(Array.isArray(d.rates))setRates(d.rates);if(Array.isArray(d.experiences))setExperiences(d.experiences);if(Array.isArray(d.terms))setTerms(d.terms)}}catch{}finally{setDraftHydrated(true)}},[draftKey]);
 useEffect(()=>{if(!draftHydrated)return;try{localStorage.setItem(draftKey,JSON.stringify({p,socials,rates,experiences,terms,updatedAt:Date.now()}));setDirty(true)}catch{}},[draftHydrated,draftKey,p,socials,rates,experiences,terms]);
 function persistDraft(){try{localStorage.setItem(draftKey,JSON.stringify({p,socials,rates,experiences,terms,updatedAt:Date.now()}))}catch{}}
 async function saveProfile(){const r=await fetch("/api/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)});return r.ok}
 async function saveSocials(){const items=socials.map(s=>({...s,url:buildSocialUrl(s.platform,s.handle)}));const r=await fetch("/api/socials",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items})});return r.ok}
 async function saveRates(){return (await fetch("/api/rates",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:rates})})).ok}
 async function saveExperiences(){return (await fetch("/api/experiences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:experiences})})).ok}
 async function saveTerms(){return (await fetch("/api/terms",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:terms})})).ok}
 async function saveAll(){if(socials.some(s=>Number(s.averageViewsMax||0)<Number(s.averageViewsMin||0))){flash(p.language==="id"?"Maximum views harus sama atau lebih besar dari minimum views.":"Maximum views must be greater than or equal to minimum views.");return false}const ok=(await Promise.all([saveProfile(),saveSocials(),saveRates(),saveExperiences(),saveTerms()])).every(Boolean);if(ok)setDirty(false);return ok}
 function switchTab(next:string){persistDraft();setTab(next);setMessage("");window.scrollTo({top:0,behavior:"smooth"})}
 async function printDownload(){if(savingAction)return;const target=window.open("about:blank","_blank");setSavingAction("print");setMessage(t.saving);persistDraft();try{if(await saveAll()){const url=`/preview?autoprint=1&ts=${Date.now()}`;if(target){target.location.href=url;target.focus()}else window.location.href=url;setMessage("")}else{target?.close();flash(p.language==="id"?"Gagal menyimpan sebelum print.":"Save failed before printing.")}}catch{target?.close();flash(p.language==="id"?"Print / Download gagal diproses.":"Print / Download could not be processed.")}finally{setSavingAction("")}}
 async function publish(){if(savingAction)return;const target=window.open("about:blank","_blank");setSavingAction("publish");setMessage(t.saving);persistDraft();try{if(!(await saveAll())){target?.close();flash(p.language==="id"?"Gagal menyimpan perubahan.":"Failed to save changes.");return}const r=await fetch("/api/publish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({published:true})});const data=await r.json().catch(()=>({}));if(r.ok){setP(v=>({...v,published:true}));setDirty(false);setMessage("");const url=data?.url||`/${encodeURIComponent(p.username)}`;if(target){target.location.href=`${url}?ts=${Date.now()}`;target.focus()}else window.location.href=url}else{target?.close();flash(data?.error||(p.language==="id"?"Publish gagal.":"Publish failed."))}}catch{target?.close();flash(p.language==="id"?"Save & Publish gagal diproses.":"Save & Publish could not be processed.")}finally{setSavingAction("")}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/login"}
 async function upload(kind:"avatar"|"cover",e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setUploading(kind);const local=URL.createObjectURL(file),key=kind==="avatar"?"avatarUrl":"coverUrl";setP(v=>({...v,[key]:local}));try{const fd=new FormData();fd.append("file",file);fd.append("kind",kind);const r=await fetch("/api/upload",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||t.uploadFail);setP(v=>({...v,[key]:d.url}));flash(t.uploadOk)}catch(err:any){flash(err?.message||t.uploadFail)}finally{URL.revokeObjectURL(local);setUploading("");e.target.value=""}}
 const activeTheme=resolveTheme(p.theme),activePalette=resolvePalette(activeTheme.id,p.colorPattern); const stepIndex=editMenu.indexOf(tab);
 const previewProfile={...p,colorPattern:p.colorPattern};
 function sendLivePreview(){const w=previewFrameRef.current?.contentWindow;if(!w)return;w.postMessage({type:"wholegacy-ratecard-preview",payload:{profile:previewProfile,socials,rates,experiences,terms,theme:p.theme,colorPattern:p.colorPattern}},window.location.origin)}
 useEffect(()=>{if(tab!=="design")return;const id=window.setTimeout(sendLivePreview,20);return()=>window.clearTimeout(id)},[tab,previewProfile,socials,rates,experiences,terms,p.theme,p.colorPattern]);
 return <main className="dashboard"><div className="mobileCommandBar"><div className="cmsV17StepSelect"><small>{tab==="overview"?"CMS":`${Math.max(stepIndex+1,1)} / ${editMenu.length}`}</small><select value={tab} onChange={e=>switchTab(e.target.value)}>{menu.map(m=><option key={m} value={m}>{labels[m]}</option>)}</select></div></div><div className="container dashboardGrid"><aside className="sidebar"><div className="sidebarBrand"><img src="/brand-logo.png" alt="RWL Rate Card" className="sidebarBrandLogo"/></div><small className="sidebarProductName">Rate Card Online Generator</small><nav>{menu.map((m,idx)=><button key={m} className={tab===m?"sideActive":""} onClick={()=>switchTab(m)}>{m==="overview"?"":`${idx}. `}{labels[m]}</button>)}</nav><button className="logoutBtn" onClick={logout}>{t.logout}</button></aside><section className="dashMain">{message&&<div className="toast">{message}</div>}<div className="dashTop"><div><span className="statusPill">{p.published&&!dirty?"Published":dirty?"Unsaved changes":"Draft"}</span><h1>{tab==="overview"?`Hi, ${p.displayName}`:t.editor}</h1><div className="cmsV17Status">{dirty?(p.language==="id"?"Perubahan tersimpan sebagai draft lokal.":"Changes are stored as a local draft."):(p.language==="id"?"Data tersinkron.":"Data synced.")}</div></div><div className="topActions"><label className="langSelect"><span>{t.language}</span><select value={p.language} onChange={e=>setP(v=>({...v,language:e.target.value as Lang}))}><option value="id">Indonesia</option><option value="en">English</option></select></label></div></div>
 {tab==="overview"&&<><p className="lead">{p.language==="id"?"Lengkapi data secara berurutan. Desain menjadi tahap terakhir untuk styling, preview, print, dan publish.":"Complete the data in order. Design is the final stage for styling, preview, print and publish."}</p><div className="dashCards"><div className="dashCard"><span>Public URL</span><strong className="smallStrong">/{p.username}</strong><a href={`/${p.username}`} target="_blank">Open profile</a></div><div className="dashCard"><span>Social accounts</span><strong>{socials.length}</strong></div><div className="dashCard"><span>Rate items</span><strong>{rates.length}</strong></div></div><div className="publicUrlBox publicUrlBoxCopy"><span>Creator link</span><div className="publicUrlCopyRow"><code>{publicUrl}</code><button type="button" className="copyUrlBtn" onClick={copyPublicUrl}>Copy</button></div></div></>}
 {tab==="profile"&&<Card title={t.profile} subtitle={p.language==="id"?"Upload foto dan lengkapi identitas creator.":"Upload photos and complete your creator identity."}><div className="uploadGrid"><Upload title="Avatar" value={p.avatarUrl} round busy={uploading==="avatar"} onClick={()=>avatarRef.current?.click()}/><Upload title={p.language==="id"?"Cover / foto utama":"Cover / main photo"} value={p.coverUrl} busy={uploading==="cover"} onClick={()=>coverRef.current?.click()}/></div><input ref={avatarRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload("avatar",e)}/><input ref={coverRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload("cover",e)}/><Grid><Field label="Display name"><input value={p.displayName} onChange={e=>setP(v=>({...v,displayName:e.target.value}))}/></Field><Field label="Username"><input value={p.username} onChange={e=>setP(v=>({...v,username:e.target.value}))}/></Field><CharInput label="Category / Niche" value={p.category} max={LIMITS.category} onChange={v=>setP(x=>({...x,category:v}))}/><CharInput label="Location" value={p.location} max={LIMITS.location} onChange={v=>setP(x=>({...x,location:v}))}/></Grid><CharText label="Bio" value={p.bio} max={LIMITS.bio} helper={p.language==="id"?"Ringkas personal branding dan tipe konten utama.":"Summarize your personal brand and main content."} onChange={v=>setP(x=>({...x,bio:v}))}/></Card>}
 {tab==="account"&&<Card title={t.account} subtitle={p.language==="id"?"Pilih platform dan isi handle. Link direct dibuat otomatis oleh sistem.":"Choose a platform and enter the handle. Direct links are generated automatically."}>{socials.map((s,i)=><div className="itemEditor" key={i}><div className="socialEditorHead"><div className="socialLogoBadge"><SocialIcon platform={s.platform} size={22}/></div><strong>{s.platform}</strong></div><Grid><Field label="Platform"><select value={s.platform} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,platform:e.target.value}:x))}>{platforms.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Handle"><input value={s.handle} placeholder="username" onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,handle:e.target.value}:x))}/><small className="socialAutoLink">{buildSocialUrl(s.platform,s.handle)||"Direct link akan muncul otomatis"}</small></Field><Field label="Followers"><input type="number" min="0" value={s.followers} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,followers:Number(e.target.value)}:x))}/></Field><Field label="Engagement rate (%)"><input type="number" min="0" step="0.01" value={s.engagementRate} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,engagementRate:Number(e.target.value)}:x))}/></Field><div className="avgViewsGroup"><span>Average Views</span><div className="avgViewsInputs"><input type="number" min="0" placeholder="Min" value={s.averageViewsMin} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,averageViewsMin:Number(e.target.value)}:x))}/><input type="number" min="0" placeholder="Max" value={s.averageViewsMax} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,averageViewsMax:Number(e.target.value)}:x))}/></div>{Number(s.averageViewsMax)<Number(s.averageViewsMin)&&<small className="fieldError">Maximum harus ≥ minimum.</small>}</div></Grid><CharInput label="Content Style" value={s.contentStyle} max={LIMITS.contentStyle} helper={p.language==="id"?"Contoh: Aesthetic, GRWM, tutorial, relatable lifestyle.":"Example: Aesthetic, GRWM, tutorial, relatable lifestyle."} onChange={v=>setSocials(a=>a.map((x,j)=>j===i?{...x,contentStyle:v}:x))}/><button className="textButton danger" onClick={()=>setSocials(v=>v.filter((_,j)=>j!==i))}>{t.remove}</button></div>)}<div className="rowActions"><button className="addBtn" onClick={()=>setSocials(v=>[...v,emptySocial()])}>{t.addAccount}</button></div></Card>}
 {tab==="rates"&&<Card title={t.rates} subtitle={p.language==="id"?"Jenis konten, deskripsi, platform, dan harga.":"Content type, description, platform, and price."}>{rates.map((r,i)=><div className="itemEditor" key={i}><Grid><Field label="Platform"><select value={r.platform} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,platform:e.target.value}:x))}>{platforms.map(x=><option key={x}>{x}</option>)}<option>Other</option></select></Field><CharInput label={p.language==="id"?"Jenis Konten":"Content Type"} value={r.serviceName} max={LIMITS.serviceName} onChange={v=>setRates(a=>a.map((x,j)=>j===i?{...x,serviceName:v}:x))}/><Field label={p.language==="id"?"Harga":"Price"}><input type="number" min="0" value={r.price} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></Field><Field label="Currency"><select value={r.currency} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,currency:e.target.value}:x))}><option>IDR</option><option>USD</option><option>SGD</option></select></Field></Grid><CharText label={p.language==="id"?"Deskripsi":"Description"} value={r.description} max={LIMITS.description} helper={p.language==="id"?"Jelaskan deliverables, durasi, revisi, atau scope konten.":"Describe deliverables, duration, revisions, or content scope."} onChange={v=>setRates(a=>a.map((x,j)=>j===i?{...x,description:v}:x))}/><button className="textButton danger" onClick={()=>setRates(v=>v.filter((_,j)=>j!==i))}>{t.remove}</button></div>)}<div className="rowActions"><button className="addBtn" onClick={()=>setRates(v=>[...v,emptyRate()])}>{t.addRate}</button></div></Card>}
 {tab==="contact"&&<Card title={t.contact} subtitle={p.language==="id"?"Email dan WhatsApp bisnis.":"Business email and WhatsApp."}><Grid><Field label="Email"><input type="email" value={p.contactEmail} onChange={e=>setP(v=>({...v,contactEmail:e.target.value}))}/></Field><Field label="WhatsApp"><input value={p.whatsapp} placeholder="62812..." onChange={e=>setP(v=>({...v,whatsapp:e.target.value}))}/></Field></Grid></Card>}
 {tab==="experience"&&<Card title={t.experience} subtitle={p.language==="id"?"Tambahkan pengalaman campaign, event, endorsement atau brand partnership.":"Add campaigns, events, endorsements or brand partnerships."}>{experiences.map((x,i)=><div className="inlineList" key={i}><CharText label={`#${i+1}`} value={x.label} max={LIMITS.experience} onChange={v=>setExperiences(a=>a.map((z,j)=>j===i?{label:v}:z))}/><button className="textButton danger" onClick={()=>setExperiences(v=>v.filter((_,j)=>j!==i))}>{t.remove}</button></div>)}<div className="rowActions"><button className="addBtn" onClick={()=>setExperiences(v=>[...v,{label:""}])}>{t.addExperience}</button></div></Card>}
 {tab==="terms"&&<Card title={t.terms} subtitle={p.language==="id"?"Gunakan poin singkat agar tetap nyaman dibaca pada web, mobile, dan A4.":"Use concise points for web, mobile and A4 output."}>{terms.map((x,i)=><div className="inlineList" key={i}><CharText label={`#${i+1}`} value={x.content} max={LIMITS.terms} onChange={v=>setTerms(a=>a.map((z,j)=>j===i?{content:v}:z))}/><button className="textButton danger" onClick={()=>setTerms(v=>v.filter((_,j)=>j!==i))}>{t.remove}</button></div>)}<div className="rowActions"><button className="addBtn" onClick={()=>setTerms(v=>[...v,{content:""}])}>{t.addTerm}</button></div></Card>}
 {tab==="design"&&<Card title={t.design} subtitle={p.language==="id"?"Pilih desain dan color palette, lalu periksa hasilnya secara live sebelum publish.":"Choose a design and color palette, then review it live before publishing."}><div className="cmsV17DesignGrid"><div className="cmsV17Controls"><div className="cmsV17ControlCard"><Field label={p.language==="id"?"Pilihan desain":"Design"}><select value={activeTheme.id} onChange={e=>{const th=resolveTheme(e.target.value);setP(v=>({...v,theme:th.id,colorPattern:th.palettes[0].id}))}}>{THEMES.map(th=><option value={th.id} key={th.id}>{th.name}</option>)}</select></Field><p className="socialAutoLink">{activeTheme.description}</p></div><div className="cmsV17ControlCard"><h3>Color Pattern</h3><div className="cmsV17PaletteList">{activeTheme.palettes.map(pa=><button type="button" key={pa.id} className={`cmsV17PaletteBtn ${activePalette.id===pa.id?"selected":""}`} onClick={()=>setP(v=>({...v,colorPattern:pa.id}))}><span className="cmsV17Swatches"><i style={{background:pa.vars["--rc-accent"]}}/><i style={{background:pa.vars["--rc-accent2"]}}/><i style={{background:pa.vars["--rc-bg"]}}/></span><span>{pa.name}</span></button>)}</div></div><div className="cmsV17ControlCard"><Field label={t.language}><select value={p.language} onChange={e=>setP(v=>({...v,language:e.target.value as Lang}))}><option value="id">Indonesia</option><option value="en">English</option></select></Field></div></div><div className="cmsV17PreviewPanel"><div className="cmsV17PreviewToolbar"><strong>Live Preview</strong><div className="cmsV17PreviewModes"><button type="button" className={previewMode==="desktop"?"active":""} onClick={()=>setPreviewMode("desktop")}>Webview 16:9</button><button type="button" className={previewMode==="mobile"?"active":""} onClick={()=>setPreviewMode("mobile")}>Mobile 9:16</button></div></div><VirtualPreviewFrame mode={previewMode} frameRef={previewFrameRef} onLoad={sendLivePreview}/></div></div><div className="cmsV17FinalActions"><button type="button" className="button secondary" onClick={printDownload} disabled={Boolean(savingAction)}>{savingAction==="print"?t.saving:t.print}</button><button type="button" className="button primary" onClick={publish} disabled={Boolean(savingAction)}>{savingAction==="publish"?t.saving:t.savePublish}</button></div></Card>}
 {tab!=="overview"&&tab!=="design"&&<div className="cmsWizardNav"><button className="button secondary" disabled={stepIndex<=0} onClick={()=>stepIndex>0&&switchTab(editMenu[stepIndex-1])}>{t.prev}</button><span>{stepIndex+1} / {editMenu.length}</span><button className="button primary" onClick={()=>stepIndex<editMenu.length-1&&switchTab(editMenu[stepIndex+1])}>{t.next}</button></div>}
 {tab==="design"&&<div className="cmsWizardNav v17Final"><button className="button secondary" onClick={()=>switchTab("terms")}>{t.prev}</button><span>{editMenu.length} / {editMenu.length}</span></div>}
 <footer className="cmsFooter"><SupportLink/></footer></section></div></main>
}
function Upload({title,value,busy,onClick,round=false}:{title:string;value:string;busy:boolean;onClick:()=>void;round?:boolean}){return <button type="button" className="uploadBox" onClick={onClick}><div className={`uploadThumb ${round?"round":""}`}>{value?<img src={value} alt={title}/>:<span>+</span>}</div><div><strong>{busy?"Uploading...":title}</strong><small>{value?"Click to replace":"JPG, PNG, WebP · max 5 MB"}</small></div></button>}
function Card({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="editorCard templateCmsCard"><div className="templateCmsHead"><h2>{title}</h2><p>{subtitle}</p></div>{children}</div>}
function Grid({children}:{children:React.ReactNode}){return <div className="formGrid">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function CharInput({label,value,max,onChange,helper=""}:{label:string;value:string;max:number;onChange:(v:string)=>void;helper?:string}){return <label className="field"><span>{label}</span><input value={value} maxLength={max} onChange={e=>onChange(e.target.value)}/><div className="charFieldMeta"><small>{helper}</small><small>{value.length} / {max}</small></div></label>}
function CharText({label,value,max,onChange,helper=""}:{label:string;value:string;max:number;onChange:(v:string)=>void;helper?:string}){return <label className="field"><span>{label}</span><textarea value={value} maxLength={max} onChange={e=>onChange(e.target.value)}/><div className="charFieldMeta"><small>{helper}</small><small>{value.length} / {max}</small></div></label>}
