"use client";
import { useMemo, useState } from "react";

type AnyRow = Record<string, any>;
const emptySocial = () => ({ platform: "Instagram", handle: "", url: "", followers: 0, averageViews: 0, engagementRate: 0 });
const emptyRate = () => ({ platform: "Instagram", serviceName: "Reels", price: 0, currency: "IDR", description: "" });

export default function DashboardClient({ user, profile, initialSocials, initialRates }: { user: AnyRow; profile: AnyRow; initialSocials: AnyRow[]; initialRates: AnyRow[] }) {
  const [tab, setTab] = useState("overview");
  const [message, setMessage] = useState("");
  const [p, setP] = useState({ username: profile.username || "", displayName: profile.display_name || "", bio: profile.bio || "", category: profile.category || "", location: profile.location || "", avatarUrl: profile.avatar_url || "", coverUrl: profile.cover_url || "", contactEmail: profile.contact_email || user.email, whatsapp: profile.whatsapp || "", theme: profile.theme || "minimal", published: Boolean(profile.published) });
  const [socials, setSocials] = useState(initialSocials.map(x => ({ platform: x.platform, handle: x.handle, url: x.url, followers: Number(x.followers || 0), averageViews: Number(x.average_views || 0), engagementRate: Number(x.engagement_rate || 0) })));
  const [rates, setRates] = useState(initialRates.map(x => ({ platform: x.platform, serviceName: x.service_name, price: Number(x.price || 0), currency: x.currency || "IDR", description: x.description || "" })));
  const publicUrl = useMemo(() => `https://ratecard.wholegacy.com/${p.username}`, [p.username]);
  const flash = (t: string) => { setMessage(t); setTimeout(() => setMessage(""), 3000); };
  async function saveProfile() { const r = await fetch("/api/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(p) }); const d = await r.json(); flash(r.ok ? "Profile tersimpan." : d.error || "Gagal menyimpan."); }
  async function saveSocials() { const r = await fetch("/api/socials", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: socials }) }); const d = await r.json(); flash(r.ok ? "Social media tersimpan." : d.error || "Gagal menyimpan."); }
  async function saveRates() { const r = await fetch("/api/rates", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items: rates }) }); const d = await r.json(); flash(r.ok ? "Rate card tersimpan." : d.error || "Gagal menyimpan."); }
  async function publish() { await saveProfile(); await saveSocials(); await saveRates(); const r = await fetch("/api/publish", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ published: true }) }); const d = await r.json(); if (r.ok) { setP(v => ({ ...v, published: true })); flash("Rate card berhasil dipublish."); } else flash(d.error || "Publish gagal."); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/login"; }
  const menu = ["overview", "profile", "social", "rates", "design"];
  return <main className="dashboard"><div className="container dashboardGrid">
    <aside className="sidebar"><div className="brand">Wholegacy<span>.</span></div><small>Ratecard CMS</small><nav>{menu.map(m => <button key={m} className={tab===m?"sideActive":""} onClick={()=>setTab(m)}>{m === "social" ? "Social Media" : m === "rates" ? "Rate Card" : m[0].toUpperCase()+m.slice(1)}</button>)}</nav><button className="logoutBtn" onClick={logout}>Logout</button></aside>
    <section className="dashMain">{message && <div className="toast">{message}</div>}
      <div className="dashTop"><div><span className="statusPill">{p.published ? "Published" : "Draft"}</span><h1>{tab === "overview" ? `Hi, ${p.displayName}` : tab[0].toUpperCase()+tab.slice(1)}</h1></div><div className="topActions"><a className="button secondary" target="_blank" href={`/${p.username}`}>Preview</a><button className="button primary" onClick={publish}>Publish</button></div></div>
      {tab === "overview" && <div><p className="dashLead">Semua data rate card kamu ada di satu tempat. Simpan perubahan lalu publish saat sudah siap.</p><div className="dashCards"><div className="dashCard"><span>Public URL</span><strong className="smallStrong">/{p.username}</strong><a href={`/${p.username}`} target="_blank">Open profile</a></div><div className="dashCard"><span>Social accounts</span><strong>{socials.length}</strong></div><div className="dashCard"><span>Rate items</span><strong>{rates.length}</strong></div></div><div className="publicUrlBox"><span>Creator link</span><code>{publicUrl}</code></div></div>}
      {tab === "profile" && <EditorCard title="Creator profile" subtitle="Foto untuk v2 ini menggunakan URL gambar. Upload langsung akan ditambahkan di tahap storage."><Grid>{[["Display name","displayName"],["Username","username"],["Category","category"],["Location","location"],["Avatar image URL","avatarUrl"],["Cover image URL","coverUrl"],["Business email","contactEmail"],["WhatsApp","whatsapp"]].map(([label,key]) => <Field key={key} label={label}><input value={(p as any)[key]} onChange={e=>setP(v=>({...v,[key]:e.target.value}))}/></Field>)}</Grid><Field label="Bio"><textarea value={p.bio} onChange={e=>setP(v=>({...v,bio:e.target.value}))}/></Field><button className="button primary" onClick={saveProfile}>Save profile</button></EditorCard>}
      {tab === "social" && <EditorCard title="Social media" subtitle="Tambahkan statistik yang ingin tampil di public rate card.">{socials.map((s,i)=><div className="itemEditor" key={i}><Grid><Field label="Platform"><select value={s.platform} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,platform:e.target.value}:x))}><option>Instagram</option><option>TikTok</option><option>Facebook</option><option>YouTube</option><option>X</option></select></Field><Field label="Handle"><input value={s.handle} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,handle:e.target.value}:x))}/></Field><Field label="Followers"><input type="number" value={s.followers} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,followers:Number(e.target.value)}:x))}/></Field><Field label="Average views"><input type="number" value={s.averageViews} onChange={e=>setSocials(v=>v.map((x,j)=>j===i?{...x,averageViews:Number(e.target.value)}:x))}/></Field></Grid><button className="textButton danger" onClick={()=>setSocials(v=>v.filter((_,j)=>j!==i))}>Remove</button></div>)}<div className="rowActions"><button className="button secondary" onClick={()=>setSocials(v=>[...v,emptySocial()])}>+ Add account</button><button className="button primary" onClick={saveSocials}>Save socials</button></div></EditorCard>}
      {tab === "rates" && <EditorCard title="Collaboration rates" subtitle="Buat layanan Instagram, TikTok, Facebook atau layanan custom.">{rates.map((r,i)=><div className="itemEditor" key={i}><Grid><Field label="Platform"><input value={r.platform} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,platform:e.target.value}:x))}/></Field><Field label="Service"><input value={r.serviceName} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,serviceName:e.target.value}:x))}/></Field><Field label="Price"><input type="number" value={r.price} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></Field><Field label="Currency"><select value={r.currency} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,currency:e.target.value}:x))}><option>IDR</option><option>USD</option><option>SGD</option></select></Field></Grid><Field label="Description"><input value={r.description} onChange={e=>setRates(v=>v.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/></Field><button className="textButton danger" onClick={()=>setRates(v=>v.filter((_,j)=>j!==i))}>Remove</button></div>)}<div className="rowActions"><button className="button secondary" onClick={()=>setRates(v=>[...v,emptyRate()])}>+ Add rate</button><button className="button primary" onClick={saveRates}>Save rates</button></div></EditorCard>}
      {tab === "design" && <EditorCard title="Choose design" subtitle="Data kamu tetap sama. Yang berubah hanya tampilan public rate card."><div className="themeGrid">{[["minimal","Minimal","Clean editorial"],["creator","Creator","Visual & energetic"],["dark-pro","Dark Pro","Premium dark"]].map(([id,name,desc])=><button key={id} className={`themeCard ${p.theme===id?"selected":""}`} onClick={()=>setP(v=>({...v,theme:id}))}><div className={`themePreview ${id}`}><span>{p.displayName || "Creator Name"}</span><i/><i/><i/></div><strong>{name}</strong><small>{desc}</small></button>)}</div><button className="button primary" onClick={saveProfile}>Save design</button></EditorCard>}
    </section>
  </div></main>;
}

function EditorCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="editorCard"><h2>{title}</h2><p>{subtitle}</p>{children}</div>}
function Grid({children}:{children:React.ReactNode}){return <div className="formGrid">{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
