import React from "react";

type Social={platform?:string;handle?:string;followers?:number;engagementRate?:number;averageViews?:number;averageViewsMin?:number;averageViewsMax?:number;contentStyle?:string;url?:string};
type Rate={platform?:string;serviceName?:string;service_name?:string;price?:number;currency?:string;description?:string};
type Profile={displayName?:string;display_name?:string;bio?:string;category?:string;location?:string;avatarUrl?:string;avatar_url?:string;coverUrl?:string;cover_url?:string;contactEmail?:string;contact_email?:string;whatsapp?:string;theme?:string};
type Experience={label?:string}; type Term={content?:string};
const n=(v:any)=>Number(v||0); const name=(p:Profile)=>p.displayName||p.display_name||"Creator Name"; const avatar=(p:Profile)=>p.avatarUrl||p.avatar_url||""; const cover=(p:Profile)=>p.coverUrl||p.cover_url||"";
const compact=(v:number)=>new Intl.NumberFormat("id-ID",{notation:"compact",maximumFractionDigits:1}).format(v||0);
const money=(v:number,c="IDR")=>{try{return new Intl.NumberFormat("id-ID",{style:"currency",currency:c,maximumFractionDigits:0}).format(v||0)}catch{return `${c} ${n(v).toLocaleString("id-ID")}`}};
const rateName=(r:Rate)=>r.serviceName||r.service_name||"Service";
const pct=(v:number)=>`${String(n(v)).replace(".",",")}%`;
const viewRange=(s:Social)=>{const a=n(s.averageViewsMin),b=n(s.averageViewsMax); if(a||b)return `${(a||b).toLocaleString("id-ID")} - ${(b||a).toLocaleString("id-ID")}`; return n(s.averageViews).toLocaleString("id-ID")};

export function SocialIcon({platform,size=18}:{platform?:string;size?:number}){const p=(platform||"").toLowerCase();const C={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(p==="instagram")return <svg {...C}><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>;if(p==="tiktok")return <svg {...C}><path d="M14 4v10.2a4.2 4.2 0 1 1-3.3-4.1"/><path d="M14 4c1.2 2.5 3 3.7 5 3.8"/></svg>;if(p==="youtube")return <svg {...C}><path d="M21 12s0-4-1-5-1-1-8-1-6 0-7 1-1 1-1 5 0 4 1 5 1 1 7 1 6 0 8-1 1-1 1-5Z"/><path d="m10 9 5 3-5 3Z"/></svg>;if(p==="facebook")return <svg {...C}><path d="M14 8h3V4h-3c-3 0-5 2-5 5v3H6v4h3v5h4v-5h3l1-4h-4V9c0-.7.3-1 1-1Z"/></svg>;if(p==="x"||p==="twitter")return <svg {...C}><path d="M5 4l14 16M19 4 5 20"/></svg>;return <svg {...C}><circle cx="12" cy="12" r="9"/><path d="M3 12h18"/></svg>}
const Icon=({kind}:{kind:string})=>{if(kind==="mail")return <span>✉</span>;if(kind==="wa")return <span>☎</span>;if(kind==="views")return <span>▶</span>;if(kind==="engage")return <span>↗</span>;if(kind==="style")return <span>♥</span>;return <span>●</span>};
function Avatar({p}:{p:Profile}){return avatar(p)?<img className="rtAvatar" src={avatar(p)} alt={name(p)}/>:<div className="rtAvatar rtFallback">{name(p).slice(0,1)}</div>}
function SocialChips({socials}:{socials:Social[]}){return <div className="rtSocials">{socials.map((s,i)=><div className="rtSocial" key={i}><SocialIcon platform={s.platform}/><div><strong>{compact(n(s.followers))}</strong><span>{s.platform}</span></div></div>)}</div>}
function Rates({rates}:{rates:Rate[]}){return <div className="rtRates">{rates.map((r,i)=><div className="rtRate" key={i}><div><span>{r.platform}</span><strong>{rateName(r)}</strong>{r.description&&<small>{r.description}</small>}</div><b>{money(n(r.price),r.currency||"IDR")}</b></div>)}</div>}
function Minimal({p,socials,rates}:{p:Profile;socials:Social[];rates:Rate[]}){return <div className="rateTemplate tplMinimal"><div className="minimalTop"><Avatar p={p}/><div><span className="rtKicker">CREATOR RATE CARD</span><h1>{name(p)}</h1><p>{[p.category,p.location].filter(Boolean).join(" · ")}</p></div></div>{p.bio&&<p className="rtBio">{p.bio}</p>}<SocialChips socials={socials}/><div className="rtDivider"/><div className="rtLabel">Collaboration rates</div><Rates rates={rates}/><div className="rtBrand">WHOLEGACY</div></div>}
function Creator({p,socials,rates}:{p:Profile;socials:Social[];rates:Rate[]}){return <div className="rateTemplate tplCreator"><div className="creatorHero">{cover(p)?<img src={cover(p)} alt="Cover"/>:<div className="rtCoverFallback"/>}<div className="creatorOverlay"/><div className="creatorHeroIdentity"><Avatar p={p}/><div><span>Creator media kit</span><h1>{name(p)}</h1><p>{p.category||"Content Creator"}</p></div></div></div><div className="creatorBody"><SocialChips socials={socials}/>{p.bio&&<div className="creatorAbout"><span>ABOUT</span><p>{p.bio}</p></div>}<div className="rtLabel">Services & rates</div><Rates rates={rates}/></div></div>}
function DarkPro({p,socials,rates}:{p:Profile;socials:Social[];rates:Rate[]}){return <div className="rateTemplate tplDark"><div className="darkGrid"><div className="darkIntro"><span className="rtKicker">WHOLEGACY / RATECARD</span><Avatar p={p}/><h1>{name(p)}</h1><p>{[p.category,p.location].filter(Boolean).join(" / ")}</p>{p.bio&&<div className="darkBio">{p.bio}</div>}<SocialChips socials={socials}/></div><div className="darkRates"><div className="darkNum">01</div><div className="rtLabel">Selected collaboration rates</div><Rates rates={rates}/></div></div></div>}
function Editorial({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const s=socials[0]||{};return <div className="rateTemplate tplEditorial"><header className="edHead"><div><div className="edTitle">RATE CARD</div><div className="edScript">{s.platform||"Content"} Creator</div>{s.handle&&<div className="edHandle">{s.platform?.toLowerCase()}.com/{s.handle}</div>}</div><div className="edPlatform"><SocialIcon platform={s.platform} size={34}/><b>{s.platform||"Social"}</b></div></header><div className="edGrid"><aside><div className="edPortrait">{cover(p)||avatar(p)?<img src={cover(p)||avatar(p)} alt={name(p)}/>:<div className="edPortraitFallback">{name(p).slice(0,1)}</div>}</div><h1>{name(p)}</h1><h3>{p.category||"Content Creator"}</h3>{p.bio&&<div className="edBox edBio">{p.bio}</div>}<section className="edSection"><div className="edCap">HUBUNGI SAYA</div><div className="edContact"><Icon kind="mail"/><span>{p.contactEmail||p.contact_email||"email@example.com"}</span></div><div className="edContact"><Icon kind="wa"/><span>{p.whatsapp||"08xxxxxxxxxx"}</span></div></section>{experiences.length>0&&<section className="edSection"><div className="edCap">PENGALAMAN KOLABORASI</div><ul className="edChecks">{experiences.map((x,i)=><li key={i}>{x.label}</li>)}</ul></section>}</aside><main><section className="edSection"><div className="edCap">TENTANG AKUN {String(s.platform||"").toUpperCase()}</div><div className="edMetric"><div className="edMetricIcon"><Icon kind="followers"/></div><div><small>FOLLOWERS</small><strong>{n(s.followers).toLocaleString("id-ID")}</strong></div></div><div className="edMetric"><div className="edMetricIcon"><Icon kind="engage"/></div><div><small>ENGAGEMENT RATE</small><strong>{pct(n(s.engagementRate))}</strong></div></div><div className="edMetric"><div className="edMetricIcon"><Icon kind="views"/></div><div><small>RATA-RATA VIEWS</small><strong>{viewRange(s)}</strong></div></div><div className="edMetric"><div className="edMetricIcon"><Icon kind="style"/></div><div><small>GAYA KONTEN</small><strong className="edStyle">{s.contentStyle||"Authentic & Relatable"}</strong></div></div></section><section className="edSection"><div className="edCap">RATE & PAKET KERJA SAMA</div><div className="edTable"><div className="edTr edTh"><span>JENIS KONTEN</span><span>DESKRIPSI</span><span>HARGA</span></div>{rates.map((r,i)=><div className="edTr" key={i}><strong>{rateName(r)}</strong><span>{r.description||r.platform}</span><b>{money(n(r.price),r.currency||"IDR")}</b></div>)}</div></section>{terms.length>0&&<section className="edSection"><div className="edCap">SYARAT & KETENTUAN</div><ul className="edChecks">{terms.map((x,i)=><li key={i}>{x.content}</li>)}</ul></section>}</main></div><footer className="edFooter">LET'S GROW TOGETHER</footer></div>}
export default function RatecardTemplates({profile,socials=[],rates=[],experiences=[],terms=[],theme}:{profile:Profile;socials?:Social[];rates?:Rate[];experiences?:Experience[];terms?:Term[];theme?:string}){const t=theme||profile.theme||"minimal";if(t==="editorial")return <Editorial p={profile} socials={socials} rates={rates} experiences={experiences} terms={terms}/>;if(t==="creator")return <Creator p={profile} socials={socials} rates={rates}/>;if(t==="dark-pro")return <DarkPro p={profile} socials={socials} rates={rates}/>;return <Minimal p={profile} socials={socials} rates={rates}/>}
