import React from "react";
import {resolvePalette,resolveTheme} from "@/lib/theme-config";

type Social={platform?:string;handle?:string;followers?:number;engagementRate?:number;averageViews?:number;averageViewsMin?:number;averageViewsMax?:number;contentStyle?:string;url?:string};
type Rate={platform?:string;serviceName?:string;service_name?:string;price?:number;currency?:string;description?:string};
type Profile={username?:string;displayName?:string;display_name?:string;bio?:string;category?:string;location?:string;avatarUrl?:string;avatar_url?:string;coverUrl?:string;cover_url?:string;contactEmail?:string;contact_email?:string;whatsapp?:string;theme?:string;colorPattern?:string;color_pattern?:string;language?:"id"|"en"};
type Experience={label?:string}; type Term={content?:string};
const n=(v:any)=>Number(v||0),nm=(p:Profile)=>p.displayName||p.display_name||"Creator Name",av=(p:Profile)=>p.avatarUrl||p.avatar_url||"",cv=(p:Profile)=>p.coverUrl||p.cover_url||"";
const money=(v:number,c="IDR")=>{try{return new Intl.NumberFormat(c==="IDR"?"id-ID":"en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(v||0)}catch{return `${c} ${n(v).toLocaleString()}`}};
const compact=(v:number,lang:"id"|"en")=>new Intl.NumberFormat(lang==="id"?"id-ID":"en-US",{notation:"compact",maximumFractionDigits:1}).format(v||0);
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:2}).format(n(v))}%`;
const viewRange=(s:Social,lang:"id"|"en")=>{const a=n(s.averageViewsMin),b=n(s.averageViewsMax),f=(x:number)=>compact(x,lang);return a||b?`${f(a||b)} – ${f(b||a)}`:f(n(s.averageViews))};
const waDigits=(v?:string)=>String(v||"").replace(/\D/g,"").replace(/^0/,"62");
const cleanHandle=(v?:string)=>String(v||"").trim().replace(/^@/,"").replace(/^https?:\/\/(www\.)?/i,"").replace(/^[^/]+\//,"").replace(/^@/,"").replace(/\/$/,"");
export function buildSocialUrl(platform?:string,handle?:string){const h=cleanHandle(handle);if(!h)return"";const p=String(platform||"").toLowerCase();if(p==="instagram")return`https://www.instagram.com/${h}`;if(p==="tiktok")return`https://www.tiktok.com/@${h}`;if(p==="facebook")return`https://www.facebook.com/${h}`;if(p==="youtube")return`https://www.youtube.com/@${h}`;if(p==="x"||p==="twitter")return`https://x.com/${h}`;if(p==="threads")return`https://www.threads.net/@${h}`;if(p==="twitch")return`https://www.twitch.tv/${h}`;if(p==="linkedin")return`https://www.linkedin.com/in/${h}`;return""}
function socialLink(s:Social){return s.url?.trim()||buildSocialUrl(s.platform,s.handle)}
export function SocialIcon({platform,size=18}:{platform?:string;size?:number}){const p=(platform||"").toLowerCase();const C={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(p==="instagram")return <svg {...C}><rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="3.8"/><circle cx="17.4" cy="6.7" r=".8" fill="currentColor" stroke="none"/></svg>;if(p==="tiktok")return <svg {...C}><path d="M14 4v10.2a4.2 4.2 0 1 1-3.5-4.1"/><path d="M14 4c1.1 2.4 2.9 3.6 5 3.8"/></svg>;if(p==="youtube")return <svg {...C}><rect x="3" y="6.5" width="18" height="11" rx="3"/><path d="m10 9.5 5 2.5-5 2.5Z"/></svg>;if(p==="facebook")return <svg {...C}><path d="M14.2 7.2h2.6V3.8h-2.9c-3 0-4.8 1.9-4.8 5v2.3H6.5v3.5h2.6v5.6h3.7v-5.6h3.1l.7-3.5h-3.8V8.8c0-1.05.35-1.6 1.4-1.6Z"/></svg>;if(p==="x"||p==="twitter")return <svg {...C}><path d="M5 4.5 19 19.5M18.5 4.5 5.5 19.5"/></svg>;if(p==="threads")return <svg {...C}><path d="M16.8 8.8c-.6-2-2.2-3.3-4.8-3.3-3.7 0-6 2.4-6 6.5s2.3 6.5 6 6.5c3.2 0 5.3-1.5 5.3-4.1 0-2.2-1.8-3.6-4.3-3.6-2.1 0-3.5.9-3.5 2.3 0 1.2 1 2 2.4 2 2.4 0 4.1-1.8 4.1-4.7 0-2.8-1-5.1-3.2-6.4"/></svg>;if(p==="twitch")return <svg {...C}><path d="M5 4h15v10l-4 4h-4l-3 3v-3H5Z"/><path d="M10 8v5M15 8v5"/></svg>;if(p==="linkedin")return <svg {...C}><rect x="4" y="9" width="4" height="10"/><path d="M6 5.2v.1M11 19v-6c0-2 1.2-4 4-4 2.6 0 4 1.8 4 4v6M11 9v10"/></svg>;return <svg {...C}><circle cx="12" cy="12" r="8.5"/><path d="M3.5 12h17"/></svg>}
const lang=(p:Profile)=>p.language||"id";const L=(l:"id"|"en")=>l==="id"?{social:"Statistik Social Media",followers:"Followers",eng:"Engagement Rate",views:"Rata-rata Views",style:"Content Style",rates:"Rate Kerja Sama",contact:"Hubungi Saya",exp:"Pengalaman Kolaborasi",terms:"Syarat & Ketentuan",bio:"Tentang Creator"}:{social:"Social Media Stats",followers:"Followers",eng:"Engagement Rate",views:"Average Views",style:"Content Style",rates:"Collaboration Rates",contact:"Contact Me",exp:"Collaboration Experience",terms:"Terms & Conditions",bio:"About Creator"};
function Avatar({p}:{p:Profile}){return <div className="rc17Avatar">{av(p)?<img src={av(p)} alt={nm(p)}/>:<span>{nm(p).slice(0,1)}</span>}</div>}
function SocialCards({items,l}:{items:Social[];l:"id"|"en"}){const x=L(l);return <div className="rc17SocialGrid">{items.map((s,i)=><a className="rc17SocialCard" href={socialLink(s)||undefined} target={socialLink(s)?"_blank":undefined} rel="noreferrer" key={i}><div className="rc17SocialHead"><span className="rc17Icon"><SocialIcon platform={s.platform}/></span><div><b>{s.platform||"Social"}</b><small>@{cleanHandle(s.handle)||"username"}</small></div></div><div className="rc17Stats"><div><strong>{compact(n(s.followers),l)}</strong><span>{x.followers}</span></div><div><strong>{pct(n(s.engagementRate))}</strong><span>{x.eng}</span></div><div><strong>{viewRange(s,l)}</strong><span>{x.views}</span></div></div>{s.contentStyle&&<p>{s.contentStyle}</p>}</a>)}</div>}
function Rates({items,l}:{items:Rate[];l:"id"|"en"}){return <div className="rc17Rates">{items.map((r,i)=><div className="rc17Rate" key={i}><div className="rc17RateTop"><span>{String(i+1).padStart(2,"0")} · {r.platform||"Platform"}</span><b>{money(n(r.price),r.currency||"IDR")}</b></div><strong>{r.serviceName||r.service_name||"Content Type"}</strong>{r.description&&<p>{r.description}</p>}</div>)}</div>}
function Contact({p}:{p:Profile}){const email=p.contactEmail||p.contact_email||"";const w=waDigits(p.whatsapp);return <div className="rc17Contacts">{email&&<a href={`mailto:${email}`}><span>✉</span><div><small>Email</small><b>{email}</b></div></a>}{w&&<a href={`https://wa.me/${w}`} target="_blank" rel="noreferrer"><span>◔</span><div><small>WhatsApp</small><b>+{w}</b></div></a>}</div>}
function Lower({p,experiences,terms,l}:{p:Profile;experiences:Experience[];terms:Term[];l:"id"|"en"}){const x=L(l);return <div className="rc17Lower"><div className="rc17Panel"><h3>{x.exp}</h3>{experiences.map((e,i)=><p key={i}><span>{String(i+1).padStart(2,"0")}</span>{e.label}</p>)}</div><div className="rc17Panel"><h3>{x.terms}</h3>{terms.map((t,i)=><p key={i}><span>{String(i+1).padStart(2,"0")}</span>{t.content}</p>)}</div></div>}
export default function RatecardTemplates({profile,socials=[],rates=[],experiences=[],terms=[],theme,colorPattern}:{profile:Profile;socials?:Social[];rates?:Rate[];experiences?:Experience[];terms?:Term[];theme?:string;colorPattern?:string}){const th=resolveTheme(theme||profile.theme);const pal=resolvePalette(th.id,colorPattern||profile.colorPattern||profile.color_pattern);const l=lang(profile),x=L(l);const style=pal.vars as React.CSSProperties;return <article className={`rc17 rc17-${th.id}`} style={style} data-theme={th.id} data-palette={pal.id}>
<div className="rc17Hero">{cv(profile)&&<img className="rc17Cover" src={cv(profile)} alt=""/>}<div className="rc17HeroShade"/><div className="rc17HeroLabel">{profile.category||"Content Creator"}</div><div className="rc17HeroName"><small>{profile.location||"Indonesia"}</small><h1>{nm(profile)}</h1></div></div>
<div className="rc17Body"><header className="rc17Identity"><Avatar p={profile}/><div><span>{profile.category||"Creator"}</span><h2>{nm(profile)}</h2><small>{profile.location||""}</small></div></header>
{profile.bio&&<section className="rc17Intro"><div className="rc17SectionLabel">{x.bio}</div><p>{profile.bio}</p></section>}
<section><div className="rc17SectionLabel">{x.social}</div><SocialCards items={socials} l={l}/></section>
<section><div className="rc17SectionLabel">{x.rates}</div><Rates items={rates} l={l}/></section>
<section><div className="rc17SectionLabel">{x.contact}</div><Contact p={profile}/></section>
<Lower p={profile} experiences={experiences} terms={terms} l={l}/>
<div className="rc17Public">ratecard.wholegacy.com/{profile.username}</div></div></article>}
