import React from "react";
import {resolvePalette,resolveTheme} from "@/lib/theme-config";

type Social={platform?:string;handle?:string;followers?:number;engagementRate?:number;averageViews?:number;averageViewsMin?:number;averageViewsMax?:number;contentStyle?:string;url?:string};
type Rate={platform?:string;serviceName?:string;service_name?:string;price?:number;currency?:string;description?:string};
type Profile={username?:string;displayName?:string;display_name?:string;bio?:string;category?:string;location?:string;avatarUrl?:string;avatar_url?:string;coverUrl?:string;cover_url?:string;contactEmail?:string;contact_email?:string;whatsapp?:string;theme?:string;colorPattern?:string;color_pattern?:string;language?:"id"|"en"};
type Experience={label?:string}; type Term={content?:string};
type Props={profile:Profile;socials?:Social[];rates?:Rate[];experiences?:Experience[];terms?:Term[];theme?:string;colorPattern?:string};

const num=(v:any)=>Number(v||0);
const name=(p:Profile)=>p.displayName||p.display_name||"Creator Name";
const first=(p:Profile)=>name(p).split(" ")[0]||name(p);
const last=(p:Profile)=>name(p).split(" ").slice(1).join(" ")||"Creator";
const avatar=(p:Profile)=>p.avatarUrl||p.avatar_url||"";
const cover=(p:Profile)=>p.coverUrl||p.cover_url||"";
const language=(p:Profile)=>p.language||"id";
const money=(v:number,c="IDR")=>{try{return new Intl.NumberFormat(c==="IDR"?"id-ID":"en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(v||0)}catch{return `${c} ${num(v).toLocaleString()}`}};
const compact=(v:number,l:"id"|"en")=>new Intl.NumberFormat(l==="id"?"id-ID":"en-US",{notation:"compact",maximumFractionDigits:1}).format(v||0);
const pct=(v:number)=>`${new Intl.NumberFormat("id-ID",{maximumFractionDigits:2}).format(num(v))}%`;
const views=(s:Social,l:"id"|"en")=>{const v=num(s.averageViews||s.averageViewsMax||s.averageViewsMin);return `±${compact(v,l)}`};
const waDigits=(v?:string)=>String(v||"").replace(/\D/g,"").replace(/^0/,"62");
const cleanHandle=(v?:string)=>String(v||"").trim().replace(/^@/,"").replace(/^https?:\/\/(www\.)?/i,"").replace(/^[^/]+\//,"").replace(/^@/,"").replace(/\/$/,"");
export function buildSocialUrl(platform?:string,handle?:string){const h=cleanHandle(handle);if(!h)return"";const p=String(platform||"").toLowerCase();if(p==="instagram")return`https://www.instagram.com/${h}`;if(p==="tiktok")return`https://www.tiktok.com/@${h}`;if(p==="facebook")return`https://www.facebook.com/${h}`;if(p==="youtube")return`https://www.youtube.com/@${h}`;if(p==="x"||p==="twitter")return`https://x.com/${h}`;if(p==="threads")return`https://www.threads.net/@${h}`;if(p==="twitch")return`https://www.twitch.tv/${h}`;if(p==="linkedin")return`https://www.linkedin.com/in/${h}`;return""}
const socialLink=(s:Social)=>s.url?.trim()||buildSocialUrl(s.platform,s.handle);

export function SocialIcon({platform,size=18}:{platform?:string;size?:number}){const p=(platform||"").toLowerCase();const C={width:size,height:size,viewBox:"0 0 24 24",fill:"none",stroke:"currentColor",strokeWidth:1.8,strokeLinecap:"round" as const,strokeLinejoin:"round" as const,"aria-hidden":true};if(p==="instagram")return <svg {...C}><rect x="3.5" y="3.5" width="17" height="17" rx="5"/><circle cx="12" cy="12" r="3.8"/><circle cx="17.4" cy="6.7" r=".8" fill="currentColor" stroke="none"/></svg>;if(p==="tiktok")return <svg {...C}><path d="M14 4v10.2a4.2 4.2 0 1 1-3.5-4.1"/><path d="M14 4c1.1 2.4 2.9 3.6 5 3.8"/></svg>;if(p==="youtube")return <svg {...C}><rect x="3" y="6.5" width="18" height="11" rx="3"/><path d="m10 9.5 5 2.5-5 2.5Z"/></svg>;if(p==="facebook")return <svg {...C}><path d="M14.2 7.2h2.6V3.8h-2.9c-3 0-4.8 1.9-4.8 5v2.3H6.5v3.5h2.6v5.6h3.7v-5.6h3.1l.7-3.5h-3.8V8.8c0-1.05.35-1.6 1.4-1.6Z"/></svg>;if(p==="x"||p==="twitter")return <svg {...C}><path d="M5 4.5 19 19.5M18.5 4.5 5.5 19.5"/></svg>;if(p==="threads")return <svg {...C}><path d="M16.8 8.8c-.6-2-2.2-3.3-4.8-3.3-3.7 0-6 2.4-6 6.5s2.3 6.5 6 6.5c3.2 0 5.3-1.5 5.3-4.1 0-2.2-1.8-3.6-4.3-3.6-2.1 0-3.5.9-3.5 2.3 0 1.2 1 2 2.4 2 2.4 0 4.1-1.8 4.1-4.7 0-2.8-1-5.1-3.2-6.4"/></svg>;if(p==="twitch")return <svg {...C}><path d="M5 4h15v10l-4 4h-4l-3 3v-3H5Z"/><path d="M10 8v5M15 8v5"/></svg>;if(p==="linkedin")return <svg {...C}><rect x="4" y="9" width="4" height="10"/><path d="M6 5.2v.1M11 19v-6c0-2 1.2-4 4-4 2.6 0 4 1.8 4 4v6M11 9v10"/></svg>;return <svg {...C}><circle cx="12" cy="12" r="8.5"/><path d="M3.5 12h17"/></svg>}

const copy=(l:"id"|"en")=>l==="id"?{header:"MEDIA KIT / RATE CARD",footer:"",social:"Statistik Social Media",rates:"Rate Kerja Sama",exp:"Kemitraan",terms:"Syarat & Ketentuan",contact:"Hubungi Saya",bio:"Tentang Creator",followers:"Followers",eng:"Engagement",views:"Views"}:{header:"MEDIA KIT / RATE CARD",footer:"",social:"Social Presence",rates:"Collaboration Rates",exp:"Partnerships",terms:"Terms & Conditions",contact:"Contact",bio:"About Creator",followers:"Followers",eng:"Engagement",views:"Views"};
function Img({src,alt,className}:{src:string;alt:string;className?:string}){return src?<img src={src} alt={alt} className={className}/>:<div className={`${className||""} rc172ImgFallback`} aria-label={alt}>{alt.slice(0,1)}</div>}
function MiniSocial({s,l,variant="soft"}:{s:Social;l:"id"|"en";variant?:string}){const c=copy(l);return <a className={`rc172Social rc172Social-${variant}`} href={socialLink(s)||undefined} target={socialLink(s)?"_blank":undefined} rel="noreferrer"><div className="rc172SocialHead"><span className="rc172SocialIcon"><SocialIcon platform={s.platform}/></span><div className="rc172SocialId"><b>{s.platform||"Social"}</b><small>@{cleanHandle(s.handle)||"username"}</small></div></div><div className="rc172Metrics"><div><strong>{compact(num(s.followers),l)}</strong><span>{c.followers}</span></div><div><strong>{pct(num(s.engagementRate))}</strong><span>{c.eng}</span></div><div><strong>{views(s,l)}</strong><span>{c.views}</span></div></div>{s.contentStyle&&<p>{s.contentStyle}</p>}</a>}
function MiniRate({r,i,variant="soft"}:{r:Rate;i:number;variant?:string}){return <div className={`rc172Rate rc172Rate-${variant}`}><div className="rc172RateHead"><span className="rc172RatePlatform"><SocialIcon platform={r.platform} size={13}/><em>{String(i+1).padStart(2,"0")} · {r.platform||"Platform"}</em></span><b>{money(num(r.price),r.currency||"IDR")}</b></div><strong>{r.serviceName||r.service_name||"Content Type"}</strong>{r.description&&<p>{r.description}</p>}</div>}
function ContactGlyph({type}:{type:"email"|"whatsapp"}){return type==="email"?<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>:<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-11.7 7.1L4 20l1.4-4.1A8 8 0 1 1 20 11.5Z"/><path d="M9 8.5c.5 2.4 2.1 4.1 4.7 5l1.1-1.1c.2-.2.5-.2.7-.1l2 .8"/></svg>}
function Contact({p,variant="soft"}:{p:Profile;variant?:string}){const email=p.contactEmail||p.contact_email||"";const w=waDigits(p.whatsapp);return <div className={`rc172Contact rc172Contact-${variant}`}>{email&&<a href={`mailto:${email}`}><span className="rc172ContactIcon"><ContactGlyph type="email"/></span><div><small>Email</small><b>{email}</b></div></a>}{w&&<a href={`https://wa.me/${w}`} target="_blank" rel="noreferrer"><span className="rc172ContactIcon"><ContactGlyph type="whatsapp"/></span><div><small>WhatsApp</small><b>+{w}</b></div></a>}</div>}
function ListBlock({title,items,variant="dash"}:{title:string;items:string[];variant?:string}){return <div className={`rc172List rc172List-${variant}`}><h3>{title}</h3>{items.filter(Boolean).map((x,i)=><div className="rc172ListRow" key={i}><span>{variant==="number"?String(i+1).padStart(2,"0"):variant==="star"?"✦":"•"}</span><p>{x}</p></div>)}</div>}
function PublicLink({p}:{p:Profile}){return <div className="rc172Public">ratecard.wholegacy.com/{p.username||"creator"}</div>}

function CreamEditorial({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Cream"><div className="rc172CreamTop"><span>{c.header}</span><span>{c.footer}</span></div><div className="rc172CreamGrid"><div className="rc172CreamCover"><Img src={cover(p)} alt="cover" className="rc172Fill"/><span className="rc172CreamBadge">{p.category||"Content Creator"}</span><div className="rc172CreamPill"><Img src={avatar(p)} alt={name(p)} className="rc172CreamPillAvatar"/><div><b>{name(p)}</b><small>{p.location||"Indonesia"}</small></div></div></div><div className="rc172CreamContent"><div className="rc172CreamIntro"><span>— {first(p)}</span><h1>{first(p)} <i>{last(p)}</i></h1><p>{p.bio}</p></div><section><h2>{c.social}</h2><div className="rc172SocialGrid">{socials.map((s,i)=><MiniSocial s={s} l={l} key={i}/>)}</div></section><section><h2>{c.rates}</h2><div className="rc172RateGrid">{rates.map((r,i)=><MiniRate r={r} i={i} key={i}/>)}</div></section><div className="rc172CreamLower"><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="dash"/><div className="rc172CreamContact"><h3>{c.contact}</h3><Contact p={p}/></div></div><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="number"/><PublicLink p={p}/></div></div></article>}

function DarkBento({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Bento"><div className="rc172BentoTop"><span>{c.header}</span><span className="rc172BentoIdentity"><Img src={avatar(p)} alt={name(p)} className="rc172TinyAvatar"/>{name(p)}</span></div><div className="rc172BentoHero"><div className="rc172BentoLead"><span>{p.category||"Creator"}</span><h1>{first(p)}<br/><b>{last(p).toUpperCase()}</b></h1><p>{p.bio}</p></div><div className="rc172BentoCover"><Img src={cover(p)} alt="cover" className="rc172Fill"/><div className="rc172Availability"><i/>Available</div></div></div><div className="rc172BentoCards">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="bento" key={i}/>)}</div><div className="rc172BentoRates">{rates.map((r,i)=><MiniRate r={r} i={i} variant="bento" key={i}/>)}</div><div className="rc172BentoBottom"><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="star"/><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="number"/><div className="rc172BentoContact"><h3>{c.contact}</h3><Contact p={p} variant="stack"/></div></div><PublicLink p={p}/></article>}

function PastelLookbook({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Lookbook"><div className="rc172LookbookHero"><Img src={cover(p)} alt="cover" className="rc172Fill"/><div className="rc172LookbookShade"/><span className="rc172LookbookTag">{c.header.split("/")[0]}</span><span className="rc172LookbookBrand">{c.footer}</span><div className="rc172LookbookAvatar"><Img src={avatar(p)} alt={name(p)} className="rc172Fill"/></div></div><div className="rc172LookbookIntro"><h1>{first(p)} <i>{last(p)}</i></h1><div className="rc172Pills"><span>{p.category||"Creator"}</span><span>{p.location||"Indonesia"}</span></div><p>{p.bio}</p></div><div className="rc172LookbookBody"><section><div className="rc172SocialGrid">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="pill" key={i}/>)}</div></section><section><h2>{c.rates}</h2><div className="rc172RateGrid">{rates.map((r,i)=><MiniRate r={r} i={i} variant="pill" key={i}/>)}</div></section><div className="rc172LookbookLower"><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="dash"/><div className="rc172LookbookContact"><h3>{c.contact}</h3><Contact p={p}/><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="dash"/></div></div><PublicLink p={p}/></div></article>}

function MinimalMono({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Mono"><div className="rc172MonoTop"><span>{c.header}</span><span>{c.footer}</span></div><div className="rc172MonoGrid"><aside><div className="rc172MonoPhoto"><Img src={avatar(p)} alt={name(p)} className="rc172Fill"/></div><h1>{name(p)}</h1><small>{p.category||"Creator"}<br/>{p.location||"Indonesia"}</small><div className="rc172MonoBio"><b>BIO —</b><p>{p.bio}</p></div><Contact p={p} variant="mono"/></aside><main><section><h2>{c.social} —</h2><div className="rc172MonoSocials">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="mono" key={i}/>)}</div></section><section><h2>{c.rates} —</h2><div className="rc172MonoRates">{rates.map((r,i)=><MiniRate r={r} i={i} variant="mono" key={i}/>)}</div></section><div className="rc172MonoBottom"><ListBlock title={`${c.exp} —`} items={experiences.map(x=>x.label||"")} variant="number"/><ListBlock title={`${c.terms} —`} items={terms.map(x=>x.content||"")} variant="number"/></div><PublicLink p={p}/></main></div></article>}

function AuraGlass({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Aura"><div className="rc172AuraBlob rc172AuraBlobA"/><div className="rc172AuraBlob rc172AuraBlobB"/><div className="rc172AuraTop"><span>{c.header}</span><span>{c.footer}</span></div><div className="rc172AuraGrid"><div className="rc172AuraProfile"><div className="rc172AuraPhoto"><Img src={avatar(p)} alt={name(p)} className="rc172Fill"/></div><span>Creator</span><h1>{first(p)} <i>{last(p)}</i></h1><p>{p.bio}</p><Contact p={p} variant="glass"/></div><div className="rc172AuraContent"><section><div className="rc172SocialGrid">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="glass" key={i}/>)}</div></section><section><div className="rc172RateGrid">{rates.map((r,i)=><MiniRate r={r} i={i} variant="glass" key={i}/>)}</div></section><div className="rc172AuraLower"><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="dash"/><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="number"/></div></div></div><PublicLink p={p}/></article>}

function BrutalistPaper({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Brutal"><div className="rc172BrutalMast"><span>{c.header} • EDISI 10</span><span>{c.footer}</span></div><div className="rc172BrutalGrid"><main><div className="rc172BrutalIntro"><div><div className="rc172BrutalPortrait"><Img src={avatar(p)} alt={name(p)} className="rc172Fill"/></div><Contact p={p} variant="brutal"/></div><div><h1>{name(p).toUpperCase()}</h1><span className="rc172BrutalChip">{p.category||"Creator"} / {p.location||"Indonesia"}</span><p>{p.bio}</p><h2>{c.social}</h2><div className="rc172BrutalSocials">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="brutal" key={i}/>)}</div></div></div><h2>{c.rates} • {rates.length} ITEMS</h2><div className="rc172BrutalRates">{rates.map((r,i)=><MiniRate r={r} i={i} variant="brutal" key={i}/>)}</div></main><aside><div className="rc172BrutalCover"><Img src={cover(p)} alt="cover" className="rc172Fill"/></div><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="number"/><div className="rc172BrutalTerms"><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="number"/></div><div className="rc172BrutalFooter">{c.footer}</div></aside></div><PublicLink p={p}/></article>}

function LuxuryGold({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Luxury"><div className="rc172LuxuryHero"><Img src={cover(p)} alt="cover" className="rc172Fill"/><div className="rc172LuxuryShade"/><div className="rc172LuxuryTop"><span>{c.header}</span><span>{c.footer}</span></div><div className="rc172LuxuryIdentity"><div className="rc172LuxuryAvatar"><Img src={avatar(p)} alt={name(p)} className="rc172Fill"/></div><div><span>{p.category||"Creator"}</span><h1>{first(p)} <i>{last(p)}</i></h1></div></div></div><div className="rc172LuxuryBody"><p className="rc172LuxuryBio">{p.bio}</p><section><h2>{c.social}</h2><div className="rc172LuxurySocials">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="luxury" key={i}/>)}</div></section><section><h2>{c.rates}</h2><div className="rc172LuxuryRates">{rates.map((r,i)=><MiniRate r={r} i={i} variant="luxury" key={i}/>)}</div></section><div className="rc172LuxuryLower"><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="star"/><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="number"/><div className="rc172LuxuryContact"><h3>{c.contact}</h3><Contact p={p} variant="stack"/><span>{c.footer}</span></div></div><PublicLink p={p}/></div></article>}

function KawaiiDashboard({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Kawaii"><div className="rc172KawaiiTop"><span>{c.header}</span><span>{c.footer}</span></div><div className="rc172KawaiiGrid"><aside><div className="rc172KawaiiAvatar"><Img src={avatar(p)} alt={name(p)} className="rc172Fill"/></div><h1>{name(p)}</h1><small>{p.category||"Creator"}<br/>{p.location||"Indonesia"}</small><p>{p.bio}</p><Contact p={p} variant="stack"/></aside><main><div className="rc172KawaiiCover"><Img src={cover(p)} alt="cover" className="rc172Fill"/><span>✦ Aesthetic Lifestyle & Visual Storytelling</span></div><section><h2>{c.social}</h2><div className="rc172SocialGrid">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="kawaii" key={i}/>)}</div></section><section><h2>{c.rates}</h2><div className="rc172RateGrid">{rates.map((r,i)=><MiniRate r={r} i={i} variant="kawaii" key={i}/>)}</div></section><div className="rc172KawaiiLower"><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="dash"/><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="dash"/></div><PublicLink p={p}/></main></div></article>}

function ModernSidebar({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172SidebarPro"><aside><div className="rc172SidebarIdentity"><Img src={avatar(p)} alt={name(p)} className="rc172SidebarAvatar"/><div><b>{name(p)}</b><small>{p.location||"Indonesia"}</small></div></div><div><h3>BIO</h3><p>{p.bio}</p></div><div><h3>{c.contact}</h3><Contact p={p} variant="stack"/></div><div className="rc172SidebarCover"><Img src={cover(p)} alt="cover" className="rc172Fill"/></div><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="dash"/></aside><main><div className="rc172SidebarTop"><span>{c.header}</span><span>{c.footer}</span></div><div className="rc172SidebarTitle"><h1>{name(p)}</h1><div className="rc172Pills"><span>{p.category||"Creator"}</span><span>{p.location||"Indonesia"}</span></div></div><section><h2>{c.social}</h2><div className="rc172SocialGrid">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="sidebar" key={i}/>)}</div></section><section><h2>{c.rates}</h2><div className="rc172RateGrid">{rates.map((r,i)=><MiniRate r={r} i={i} variant="sidebar" key={i}/>)}</div></section><section><h2>{c.terms}</h2><div className="rc172SidebarTerms">{terms.map((t,i)=><div key={i}><b>{i+1}.</b><span>{t.content}</span></div>)}</div></section><PublicLink p={p}/></main></article>}

function MagazineHero({p,socials,rates,experiences,terms}:{p:Profile;socials:Social[];rates:Rate[];experiences:Experience[];terms:Term[]}){const l=language(p),c=copy(l);return <article className="rc172 rc172Magazine"><div className="rc172MagazineHero"><Img src={cover(p)} alt="cover" className="rc172Fill"/><div className="rc172MagazineShade"/><div className="rc172MagazineTop"><span>{c.header}</span><span>{c.footer}</span></div><div className="rc172MagazineName"><div><small>{p.category||"Creator"} • {p.location||"Indonesia"}</small><h1>{first(p).toUpperCase()}<i>{last(p).toUpperCase()}</i></h1></div><div className="rc172MagazineIdentity"><Img src={avatar(p)} alt={name(p)} className="rc172MagazineAvatar"/><div><b>{name(p)}</b><small>Content Creator • Aesthetic Lifestyle</small></div></div></div></div><div className="rc172MagazineCard"><div className="rc172MagazineAbout"><div><h3>BIO —</h3><p>{p.bio}</p><Contact p={p} variant="chips"/></div><div className="rc172MagazineSocials">{socials.map((s,i)=><MiniSocial s={s} l={l} variant="magazine" key={i}/>)}</div></div><section><div className="rc172MagazineSectionHead"><h2>{c.rates}</h2><small>MAGAZINE LAYOUT • CREATOR KIT</small></div><div className="rc172RateGrid">{rates.map((r,i)=><MiniRate r={r} i={i} variant="magazine" key={i}/>)}</div></section><div className="rc172MagazineLower"><ListBlock title={c.exp} items={experiences.map(x=>x.label||"")} variant="dash"/><ListBlock title={c.terms} items={terms.map(x=>x.content||"")} variant="number"/><div className="rc172MagazineCTA"><h3>Ready to collaborate?</h3><p>Natural • Approachable • Engaging review content</p><span>{c.footer}</span></div></div><PublicLink p={p}/></div></article>}

export default function RatecardTemplates({profile,socials=[],rates=[],experiences=[],terms=[],theme,colorPattern}:Props){const th=resolveTheme(theme||profile.theme);const pal=resolvePalette(th.id,colorPattern||profile.colorPattern||profile.color_pattern);const vars={...pal.vars,"--bg":pal.vars["--rc-bg"],"--card":pal.vars["--rc-card"],"--accent":pal.vars["--rc-accent"],"--accent2":pal.vars["--rc-accent2"],"--text":pal.vars["--rc-text"],"--muted":pal.vars["--rc-muted"],"--border":pal.vars["--rc-border"]} as React.CSSProperties;const props={p:profile,socials,rates,experiences,terms};let content:React.ReactNode;switch(th.id){case"dark-bento-neon":content=<DarkBento {...props}/>;break;case"pastel-lookbook":content=<PastelLookbook {...props}/>;break;case"minimal-mono":content=<MinimalMono {...props}/>;break;case"aura-glass":content=<AuraGlass {...props}/>;break;case"brutalist-paper":content=<BrutalistPaper {...props}/>;break;case"luxury-gold":content=<LuxuryGold {...props}/>;break;case"kawaii-dashboard":content=<KawaiiDashboard {...props}/>;break;case"modern-sidebar-pro":content=<ModernSidebar {...props}/>;break;case"magazine-cover-hero":content=<MagazineHero {...props}/>;break;default:content=<CreamEditorial {...props}/>;}return <div className="rc172ThemeMount" data-theme={th.id} data-palette={pal.id} style={vars}>{content}</div>}
