import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { sql } from "@/lib/db";
import RatecardTemplates from "@/components/ratecard-templates";
import PrintDownloadButton from "@/components/PrintDownloadButton";
import AutoPrint from "@/components/AutoPrint";
import A4PrintFit from "@/components/A4PrintFit";
export const dynamic="force-dynamic";
export default async function PreviewPage(){const user=await getCurrentUser();if(!user)redirect("/login");const ps=await sql`select * from creator_profiles where user_id=${user.id} limit 1`;if(!ps.length)redirect("/onboarding");const p:any=ps[0];const socials=await sql`select * from social_accounts where user_id=${user.id} order by position asc, created_at asc`;const rates=await sql`select * from rate_items where user_id=${user.id} order by position asc, created_at asc`;const experiences=await sql`select * from collaboration_experiences where user_id=${user.id} order by position asc, created_at asc`;const terms=await sql`select * from terms_conditions where user_id=${user.id} order by position asc, created_at asc`;const sm=socials.map((s:any)=>({platform:s.platform,handle:s.handle,url:s.url,followers:Number(s.followers||0),averageViews:Number(s.average_views||s.average_views_max||s.average_views_min||0),engagementRate:Number(s.engagement_rate||0),contentStyle:s.content_style||""}));const rr=rates.map((r:any)=>({platform:r.platform,serviceName:r.service_name,price:Number(r.price||0),currency:r.currency,description:r.description}));return <main className="previewPage"><AutoPrint/><A4PrintFit/><div className="previewToolbar"><a href="/dashboard">← Back to CMS</a><span>Responsive preview · same renderer as public page</span><PrintDownloadButton /></div><div className="previewPublicShell"><RatecardTemplates profile={p} socials={sm} rates={rr} experiences={experiences.map((x:any)=>({label:x.label}))} terms={terms.map((x:any)=>({content:x.content}))} theme={p.theme}/></div></main>}
